rootProject.name = "plugins"

include(":CustomStatusPresets")
include(":RestartButton")
include(":FolderOpacity")
include(":BetterMediaViewer")
include(":NoLinkify")
include(":AccountSwitcher")
// include(":UnreadCounter")
include(":AlwaysAnimate")
include(":AvatarMention")
include(":CharCounter")
include(":QuickStar")
include(":DisablePreviewsOnData")
include(":WiderScrollbar")
include(":Token")
include(":Weather")
include(":SystemInfo")
include(":RoleColorEverywhere")
include(":CursorInput")
include(":NoBurnIn")
include(":BanCount")
include(":CustomNoticeDuration")
include(":CompactMode")
include(":DMCategories")
include(":MessageWidthFix")
include(":PermissionsSync")
include(":AppendGifAsUrl")