// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/FrecencyUserSettings.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")