// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/protobuf/any.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.google.protobuf;

@kotlin.jvm.JvmName("-initializeany")
public inline fun any(block: com.google.protobuf.AnyKt.Dsl.() -> kotlin.Unit): com.google.protobuf.Any =
  com.google.protobuf.AnyKt.Dsl._create(com.google.protobuf.Any.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `google.protobuf.Any`
 */
public object AnyKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.google.protobuf.Any.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.google.protobuf.Any.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.google.protobuf.Any = _builder.build()

    /**
     * `string type_url = 1 [json_name = "typeUrl"];`
     */
    public var typeUrl: kotlin.String
      @JvmName("getTypeUrl")
      get() = _builder.typeUrl
      @JvmName("setTypeUrl")
      set(value) {
        _builder.typeUrl = value
      }
    /**
     * `string type_url = 1 [json_name = "typeUrl"];`
     */
    public fun clearTypeUrl() {
      _builder.clearTypeUrl()
    }

    /**
     * <code>bytes value = 2 [json_name = "value"];</code>
     */
    public var value: com.google.protobuf.ByteString
      @JvmName("getValue")
      get() = _builder.value
      @JvmName("setValue")
      set(value) {
        _builder.value = value
      }
    /**
     * `bytes value = 2 [json_name = "value"];`
     */
    public fun clearValue() {
      _builder.clearValue()
    }
  }
}
public inline fun com.google.protobuf.Any.copy(block: `com.google.protobuf`.AnyKt.Dsl.() -> kotlin.Unit): com.google.protobuf.Any =
  `com.google.protobuf`.AnyKt.Dsl._create(this.toBuilder()).apply { block() }._build()

