// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/protobuf/wrappers.proto
// Protobuf Java Version: 4.28.3

package com.google.protobuf;

public interface BoolValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.protobuf.BoolValue)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>bool value = 1 [json_name = "value"];</code>
   * @return The value.
   */
  boolean getValue();
}
