// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/protobuf/wrappers.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.google.protobuf;

@kotlin.jvm.JvmName("-initializeboolValue")
public inline fun boolValue(block: com.google.protobuf.BoolValueKt.Dsl.() -> kotlin.Unit): com.google.protobuf.BoolValue =
  com.google.protobuf.BoolValueKt.Dsl._create(com.google.protobuf.BoolValue.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `google.protobuf.BoolValue`
 */
public object BoolValueKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.google.protobuf.BoolValue.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.google.protobuf.BoolValue.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.google.protobuf.BoolValue = _builder.build()

    /**
     * <code>bool value = 1 [json_name = "value"];</code>
     */
    public var value: kotlin.Boolean
      @JvmName("getValue")
      get() = _builder.value
      @JvmName("setValue")
      set(value) {
        _builder.value = value
      }
    /**
     * `bool value = 1 [json_name = "value"];`
     */
    public fun clearValue() {
      _builder.clearValue()
    }
  }
}
public inline fun com.google.protobuf.BoolValue.copy(block: `com.google.protobuf`.BoolValueKt.Dsl.() -> kotlin.Unit): com.google.protobuf.BoolValue =
  `com.google.protobuf`.BoolValueKt.Dsl._create(this.toBuilder()).apply { block() }._build()

