// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/protobuf/duration.proto
// Protobuf Java Version: 4.28.3

package com.google.protobuf;

public interface DurationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.protobuf.Duration)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>int64 seconds = 1 [json_name = "seconds"];</code>
   * @return The seconds.
   */
  long getSeconds();

  /**
   * <code>int32 nanos = 2 [json_name = "nanos"];</code>
   * @return The nanos.
   */
  int getNanos();
}
