// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/protobuf/empty.proto
// Protobuf Java Version: 4.28.3

package com.google.protobuf;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.protobuf.Empty)
    com.google.protobuf.MessageLiteOrBuilder {
}
