// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/protobuf/empty.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.google.protobuf;

@kotlin.jvm.JvmName("-initializeempty")
public inline fun empty(block: com.google.protobuf.EmptyKt.Dsl.() -> kotlin.Unit): com.google.protobuf.Empty =
  com.google.protobuf.EmptyKt.Dsl._create(com.google.protobuf.Empty.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `google.protobuf.Empty`
 */
public object EmptyKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.google.protobuf.Empty.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.google.protobuf.Empty.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.google.protobuf.Empty = _builder.build()
  }
}
public inline fun com.google.protobuf.Empty.copy(block: `com.google.protobuf`.EmptyKt.Dsl.() -> kotlin.Unit): com.google.protobuf.Empty =
  `com.google.protobuf`.EmptyKt.Dsl._create(this.toBuilder()).apply { block() }._build()

