// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/protobuf/descriptor.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.google.protobuf;

@kotlin.jvm.JvmName("-initializeenumValueDescriptorProto")
public inline fun enumValueDescriptorProto(block: com.google.protobuf.EnumValueDescriptorProtoKt.Dsl.() -> kotlin.Unit): com.google.protobuf.DescriptorProtos.EnumValueDescriptorProto =
  com.google.protobuf.EnumValueDescriptorProtoKt.Dsl._create(com.google.protobuf.DescriptorProtos.EnumValueDescriptorProto.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `google.protobuf.EnumValueDescriptorProto`
 */
public object EnumValueDescriptorProtoKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.google.protobuf.DescriptorProtos.EnumValueDescriptorProto.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.google.protobuf.DescriptorProtos.EnumValueDescriptorProto.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.google.protobuf.DescriptorProtos.EnumValueDescriptorProto = _builder.build()

    /**
     * `optional string name = 1 [json_name = "name"];`
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.name
      @JvmName("setName")
      set(value) {
        _builder.name = value
      }
    /**
     * `optional string name = 1 [json_name = "name"];`
     */
    public fun clearName() {
      _builder.clearName()
    }
    /**
     * `optional string name = 1 [json_name = "name"];`
     * @return Whether the name field is set.
     */
    public fun hasName(): kotlin.Boolean {
      return _builder.hasName()
    }

    /**
     * <code>optional int32 number = 2 [json_name = "number"];</code>
     */
    public var number: kotlin.Int
      @JvmName("getNumber")
      get() = _builder.number
      @JvmName("setNumber")
      set(value) {
        _builder.number = value
      }
    /**
     * `optional int32 number = 2 [json_name = "number"];`
     */
    public fun clearNumber() {
      _builder.clearNumber()
    }
    /**
     * `optional int32 number = 2 [json_name = "number"];`
     * @return Whether the number field is set.
     */
    public fun hasNumber(): kotlin.Boolean {
      return _builder.hasNumber()
    }

    /**
     * `optional .google.protobuf.EnumValueOptions options = 3 [json_name = "options"];`
     */
    public var options: com.google.protobuf.DescriptorProtos.EnumValueOptions
      @JvmName("getOptions")
      get() = _builder.options
      @JvmName("setOptions")
      set(value) {
        _builder.options = value
      }
    /**
     * `optional .google.protobuf.EnumValueOptions options = 3 [json_name = "options"];`
     */
    public fun clearOptions() {
      _builder.clearOptions()
    }
    /**
     * `optional .google.protobuf.EnumValueOptions options = 3 [json_name = "options"];`
     * @return Whether the options field is set.
     */
    public fun hasOptions(): kotlin.Boolean {
      return _builder.hasOptions()
    }
    public val EnumValueDescriptorProtoKt.Dsl.optionsOrNull: com.google.protobuf.DescriptorProtos.EnumValueOptions?
      get() = _builder.optionsOrNull
  }
}
public inline fun com.google.protobuf.DescriptorProtos.EnumValueDescriptorProto.copy(block: `com.google.protobuf`.EnumValueDescriptorProtoKt.Dsl.() -> kotlin.Unit): com.google.protobuf.DescriptorProtos.EnumValueDescriptorProto =
  `com.google.protobuf`.EnumValueDescriptorProtoKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.google.protobuf.DescriptorProtos.EnumValueDescriptorProtoOrBuilder.optionsOrNull: com.google.protobuf.DescriptorProtos.EnumValueOptions?
  get() = if (hasOptions()) getOptions() else null

