// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/protobuf/type.proto
// Protobuf Java Version: 4.28.3

package com.google.protobuf;

/**
 * Protobuf type {@code google.protobuf.Enum}
 */
public  final class Enum extends
    com.google.protobuf.GeneratedMessageLite<
        Enum, Enum.Builder> implements
    // @@protoc_insertion_point(message_implements:google.protobuf.Enum)
    EnumOrBuilder {
  private Enum() {
    name_ = "";
    enumvalue_ = emptyProtobufList();
    options_ = emptyProtobufList();
    edition_ = "";
  }
  private int bitField0_;
  public static final int NAME_FIELD_NUMBER = 1;
  private java.lang.String name_;
  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    return name_;
  }
  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(name_);
  }
  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @param value The name to set.
   */
  private void setName(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    name_ = value;
  }
  /**
   * <code>string name = 1 [json_name = "name"];</code>
   */
  private void clearName() {

    name_ = getDefaultInstance().getName();
  }
  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @param value The bytes for name to set.
   */
  private void setNameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    name_ = value.toStringUtf8();

  }

  public static final int ENUMVALUE_FIELD_NUMBER = 2;
  private com.google.protobuf.Internal.ProtobufList<com.google.protobuf.EnumValue> enumvalue_;
  /**
   * <code>repeated .google.protobuf.EnumValue enumvalue = 2 [json_name = "enumvalue"];</code>
   */
  @java.lang.Override
  public java.util.List<com.google.protobuf.EnumValue> getEnumvalueList() {
    return enumvalue_;
  }
  /**
   * <code>repeated .google.protobuf.EnumValue enumvalue = 2 [json_name = "enumvalue"];</code>
   */
  public java.util.List<? extends com.google.protobuf.EnumValueOrBuilder> 
      getEnumvalueOrBuilderList() {
    return enumvalue_;
  }
  /**
   * <code>repeated .google.protobuf.EnumValue enumvalue = 2 [json_name = "enumvalue"];</code>
   */
  @java.lang.Override
  public int getEnumvalueCount() {
    return enumvalue_.size();
  }
  /**
   * <code>repeated .google.protobuf.EnumValue enumvalue = 2 [json_name = "enumvalue"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.EnumValue getEnumvalue(int index) {
    return enumvalue_.get(index);
  }
  /**
   * <code>repeated .google.protobuf.EnumValue enumvalue = 2 [json_name = "enumvalue"];</code>
   */
  public com.google.protobuf.EnumValueOrBuilder getEnumvalueOrBuilder(
      int index) {
    return enumvalue_.get(index);
  }
  private void ensureEnumvalueIsMutable() {
    com.google.protobuf.Internal.ProtobufList<com.google.protobuf.EnumValue> tmp = enumvalue_;
    if (!tmp.isModifiable()) {
      enumvalue_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .google.protobuf.EnumValue enumvalue = 2 [json_name = "enumvalue"];</code>
   */
  private void setEnumvalue(
      int index, com.google.protobuf.EnumValue value) {
    value.getClass();
  ensureEnumvalueIsMutable();
    enumvalue_.set(index, value);
  }
  /**
   * <code>repeated .google.protobuf.EnumValue enumvalue = 2 [json_name = "enumvalue"];</code>
   */
  private void addEnumvalue(com.google.protobuf.EnumValue value) {
    value.getClass();
  ensureEnumvalueIsMutable();
    enumvalue_.add(value);
  }
  /**
   * <code>repeated .google.protobuf.EnumValue enumvalue = 2 [json_name = "enumvalue"];</code>
   */
  private void addEnumvalue(
      int index, com.google.protobuf.EnumValue value) {
    value.getClass();
  ensureEnumvalueIsMutable();
    enumvalue_.add(index, value);
  }
  /**
   * <code>repeated .google.protobuf.EnumValue enumvalue = 2 [json_name = "enumvalue"];</code>
   */
  private void addAllEnumvalue(
      java.lang.Iterable<? extends com.google.protobuf.EnumValue> values) {
    ensureEnumvalueIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, enumvalue_);
  }
  /**
   * <code>repeated .google.protobuf.EnumValue enumvalue = 2 [json_name = "enumvalue"];</code>
   */
  private void clearEnumvalue() {
    enumvalue_ = emptyProtobufList();
  }
  /**
   * <code>repeated .google.protobuf.EnumValue enumvalue = 2 [json_name = "enumvalue"];</code>
   */
  private void removeEnumvalue(int index) {
    ensureEnumvalueIsMutable();
    enumvalue_.remove(index);
  }

  public static final int OPTIONS_FIELD_NUMBER = 3;
  private com.google.protobuf.Internal.ProtobufList<com.google.protobuf.Option> options_;
  /**
   * <code>repeated .google.protobuf.Option options = 3 [json_name = "options"];</code>
   */
  @java.lang.Override
  public java.util.List<com.google.protobuf.Option> getOptionsList() {
    return options_;
  }
  /**
   * <code>repeated .google.protobuf.Option options = 3 [json_name = "options"];</code>
   */
  public java.util.List<? extends com.google.protobuf.OptionOrBuilder> 
      getOptionsOrBuilderList() {
    return options_;
  }
  /**
   * <code>repeated .google.protobuf.Option options = 3 [json_name = "options"];</code>
   */
  @java.lang.Override
  public int getOptionsCount() {
    return options_.size();
  }
  /**
   * <code>repeated .google.protobuf.Option options = 3 [json_name = "options"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.Option getOptions(int index) {
    return options_.get(index);
  }
  /**
   * <code>repeated .google.protobuf.Option options = 3 [json_name = "options"];</code>
   */
  public com.google.protobuf.OptionOrBuilder getOptionsOrBuilder(
      int index) {
    return options_.get(index);
  }
  private void ensureOptionsIsMutable() {
    com.google.protobuf.Internal.ProtobufList<com.google.protobuf.Option> tmp = options_;
    if (!tmp.isModifiable()) {
      options_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .google.protobuf.Option options = 3 [json_name = "options"];</code>
   */
  private void setOptions(
      int index, com.google.protobuf.Option value) {
    value.getClass();
  ensureOptionsIsMutable();
    options_.set(index, value);
  }
  /**
   * <code>repeated .google.protobuf.Option options = 3 [json_name = "options"];</code>
   */
  private void addOptions(com.google.protobuf.Option value) {
    value.getClass();
  ensureOptionsIsMutable();
    options_.add(value);
  }
  /**
   * <code>repeated .google.protobuf.Option options = 3 [json_name = "options"];</code>
   */
  private void addOptions(
      int index, com.google.protobuf.Option value) {
    value.getClass();
  ensureOptionsIsMutable();
    options_.add(index, value);
  }
  /**
   * <code>repeated .google.protobuf.Option options = 3 [json_name = "options"];</code>
   */
  private void addAllOptions(
      java.lang.Iterable<? extends com.google.protobuf.Option> values) {
    ensureOptionsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, options_);
  }
  /**
   * <code>repeated .google.protobuf.Option options = 3 [json_name = "options"];</code>
   */
  private void clearOptions() {
    options_ = emptyProtobufList();
  }
  /**
   * <code>repeated .google.protobuf.Option options = 3 [json_name = "options"];</code>
   */
  private void removeOptions(int index) {
    ensureOptionsIsMutable();
    options_.remove(index);
  }

  public static final int SOURCE_CONTEXT_FIELD_NUMBER = 4;
  private com.google.protobuf.SourceContext sourceContext_;
  /**
   * <code>.google.protobuf.SourceContext source_context = 4 [json_name = "sourceContext"];</code>
   */
  @java.lang.Override
  public boolean hasSourceContext() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.google.protobuf.SourceContext source_context = 4 [json_name = "sourceContext"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.SourceContext getSourceContext() {
    return sourceContext_ == null ? com.google.protobuf.SourceContext.getDefaultInstance() : sourceContext_;
  }
  /**
   * <code>.google.protobuf.SourceContext source_context = 4 [json_name = "sourceContext"];</code>
   */
  private void setSourceContext(com.google.protobuf.SourceContext value) {
    value.getClass();
  sourceContext_ = value;
    bitField0_ |= 0x00000001;
    }
  /**
   * <code>.google.protobuf.SourceContext source_context = 4 [json_name = "sourceContext"];</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeSourceContext(com.google.protobuf.SourceContext value) {
    value.getClass();
  if (sourceContext_ != null &&
        sourceContext_ != com.google.protobuf.SourceContext.getDefaultInstance()) {
      sourceContext_ =
        com.google.protobuf.SourceContext.newBuilder(sourceContext_).mergeFrom(value).buildPartial();
    } else {
      sourceContext_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>.google.protobuf.SourceContext source_context = 4 [json_name = "sourceContext"];</code>
   */
  private void clearSourceContext() {  sourceContext_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static final int SYNTAX_FIELD_NUMBER = 5;
  private int syntax_;
  /**
   * <code>.google.protobuf.Syntax syntax = 5 [json_name = "syntax"];</code>
   * @return The enum numeric value on the wire for syntax.
   */
  @java.lang.Override
  public int getSyntaxValue() {
    return syntax_;
  }
  /**
   * <code>.google.protobuf.Syntax syntax = 5 [json_name = "syntax"];</code>
   * @return The syntax.
   */
  @java.lang.Override
  public com.google.protobuf.Syntax getSyntax() {
    com.google.protobuf.Syntax result = com.google.protobuf.Syntax.forNumber(syntax_);
    return result == null ? com.google.protobuf.Syntax.UNRECOGNIZED : result;
  }
  /**
   * <code>.google.protobuf.Syntax syntax = 5 [json_name = "syntax"];</code>
   * @param value The enum numeric value on the wire for syntax to set.
   */
  private void setSyntaxValue(int value) {
      syntax_ = value;
  }
  /**
   * <code>.google.protobuf.Syntax syntax = 5 [json_name = "syntax"];</code>
   * @param value The syntax to set.
   */
  private void setSyntax(com.google.protobuf.Syntax value) {
    syntax_ = value.getNumber();

  }
  /**
   * <code>.google.protobuf.Syntax syntax = 5 [json_name = "syntax"];</code>
   */
  private void clearSyntax() {

    syntax_ = 0;
  }

  public static final int EDITION_FIELD_NUMBER = 6;
  private java.lang.String edition_;
  /**
   * <code>string edition = 6 [json_name = "edition"];</code>
   * @return The edition.
   */
  @java.lang.Override
  public java.lang.String getEdition() {
    return edition_;
  }
  /**
   * <code>string edition = 6 [json_name = "edition"];</code>
   * @return The bytes for edition.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEditionBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(edition_);
  }
  /**
   * <code>string edition = 6 [json_name = "edition"];</code>
   * @param value The edition to set.
   */
  private void setEdition(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    edition_ = value;
  }
  /**
   * <code>string edition = 6 [json_name = "edition"];</code>
   */
  private void clearEdition() {

    edition_ = getDefaultInstance().getEdition();
  }
  /**
   * <code>string edition = 6 [json_name = "edition"];</code>
   * @param value The bytes for edition to set.
   */
  private void setEditionBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    edition_ = value.toStringUtf8();

  }

  public static com.google.protobuf.Enum parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.google.protobuf.Enum parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.google.protobuf.Enum parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.google.protobuf.Enum parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.google.protobuf.Enum parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.google.protobuf.Enum parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.google.protobuf.Enum parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.google.protobuf.Enum parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.google.protobuf.Enum parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.google.protobuf.Enum parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.google.protobuf.Enum parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.google.protobuf.Enum parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.google.protobuf.Enum prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code google.protobuf.Enum}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.google.protobuf.Enum, Builder> implements
      // @@protoc_insertion_point(builder_implements:google.protobuf.Enum)
      com.google.protobuf.EnumOrBuilder {
    // Construct using com.google.protobuf.Enum.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string name = 1 [json_name = "name"];</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      return instance.getName();
    }
    /**
     * <code>string name = 1 [json_name = "name"];</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      return instance.getNameBytes();
    }
    /**
     * <code>string name = 1 [json_name = "name"];</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      copyOnWrite();
      instance.setName(value);
      return this;
    }
    /**
     * <code>string name = 1 [json_name = "name"];</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      copyOnWrite();
      instance.clearName();
      return this;
    }
    /**
     * <code>string name = 1 [json_name = "name"];</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setNameBytes(value);
      return this;
    }

    /**
     * <code>repeated .google.protobuf.EnumValue enumvalue = 2 [json_name = "enumvalue"];</code>
     */
    @java.lang.Override
    public java.util.List<com.google.protobuf.EnumValue> getEnumvalueList() {
      return java.util.Collections.unmodifiableList(
          instance.getEnumvalueList());
    }
    /**
     * <code>repeated .google.protobuf.EnumValue enumvalue = 2 [json_name = "enumvalue"];</code>
     */
    @java.lang.Override
    public int getEnumvalueCount() {
      return instance.getEnumvalueCount();
    }/**
     * <code>repeated .google.protobuf.EnumValue enumvalue = 2 [json_name = "enumvalue"];</code>
     */
    @java.lang.Override
    public com.google.protobuf.EnumValue getEnumvalue(int index) {
      return instance.getEnumvalue(index);
    }
    /**
     * <code>repeated .google.protobuf.EnumValue enumvalue = 2 [json_name = "enumvalue"];</code>
     */
    public Builder setEnumvalue(
        int index, com.google.protobuf.EnumValue value) {
      copyOnWrite();
      instance.setEnumvalue(index, value);
      return this;
    }
    /**
     * <code>repeated .google.protobuf.EnumValue enumvalue = 2 [json_name = "enumvalue"];</code>
     */
    public Builder setEnumvalue(
        int index, com.google.protobuf.EnumValue.Builder builderForValue) {
      copyOnWrite();
      instance.setEnumvalue(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .google.protobuf.EnumValue enumvalue = 2 [json_name = "enumvalue"];</code>
     */
    public Builder addEnumvalue(com.google.protobuf.EnumValue value) {
      copyOnWrite();
      instance.addEnumvalue(value);
      return this;
    }
    /**
     * <code>repeated .google.protobuf.EnumValue enumvalue = 2 [json_name = "enumvalue"];</code>
     */
    public Builder addEnumvalue(
        int index, com.google.protobuf.EnumValue value) {
      copyOnWrite();
      instance.addEnumvalue(index, value);
      return this;
    }
    /**
     * <code>repeated .google.protobuf.EnumValue enumvalue = 2 [json_name = "enumvalue"];</code>
     */
    public Builder addEnumvalue(
        com.google.protobuf.EnumValue.Builder builderForValue) {
      copyOnWrite();
      instance.addEnumvalue(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .google.protobuf.EnumValue enumvalue = 2 [json_name = "enumvalue"];</code>
     */
    public Builder addEnumvalue(
        int index, com.google.protobuf.EnumValue.Builder builderForValue) {
      copyOnWrite();
      instance.addEnumvalue(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .google.protobuf.EnumValue enumvalue = 2 [json_name = "enumvalue"];</code>
     */
    public Builder addAllEnumvalue(
        java.lang.Iterable<? extends com.google.protobuf.EnumValue> values) {
      copyOnWrite();
      instance.addAllEnumvalue(values);
      return this;
    }
    /**
     * <code>repeated .google.protobuf.EnumValue enumvalue = 2 [json_name = "enumvalue"];</code>
     */
    public Builder clearEnumvalue() {
      copyOnWrite();
      instance.clearEnumvalue();
      return this;
    }
    /**
     * <code>repeated .google.protobuf.EnumValue enumvalue = 2 [json_name = "enumvalue"];</code>
     */
    public Builder removeEnumvalue(int index) {
      copyOnWrite();
      instance.removeEnumvalue(index);
      return this;
    }

    /**
     * <code>repeated .google.protobuf.Option options = 3 [json_name = "options"];</code>
     */
    @java.lang.Override
    public java.util.List<com.google.protobuf.Option> getOptionsList() {
      return java.util.Collections.unmodifiableList(
          instance.getOptionsList());
    }
    /**
     * <code>repeated .google.protobuf.Option options = 3 [json_name = "options"];</code>
     */
    @java.lang.Override
    public int getOptionsCount() {
      return instance.getOptionsCount();
    }/**
     * <code>repeated .google.protobuf.Option options = 3 [json_name = "options"];</code>
     */
    @java.lang.Override
    public com.google.protobuf.Option getOptions(int index) {
      return instance.getOptions(index);
    }
    /**
     * <code>repeated .google.protobuf.Option options = 3 [json_name = "options"];</code>
     */
    public Builder setOptions(
        int index, com.google.protobuf.Option value) {
      copyOnWrite();
      instance.setOptions(index, value);
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Option options = 3 [json_name = "options"];</code>
     */
    public Builder setOptions(
        int index, com.google.protobuf.Option.Builder builderForValue) {
      copyOnWrite();
      instance.setOptions(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Option options = 3 [json_name = "options"];</code>
     */
    public Builder addOptions(com.google.protobuf.Option value) {
      copyOnWrite();
      instance.addOptions(value);
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Option options = 3 [json_name = "options"];</code>
     */
    public Builder addOptions(
        int index, com.google.protobuf.Option value) {
      copyOnWrite();
      instance.addOptions(index, value);
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Option options = 3 [json_name = "options"];</code>
     */
    public Builder addOptions(
        com.google.protobuf.Option.Builder builderForValue) {
      copyOnWrite();
      instance.addOptions(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Option options = 3 [json_name = "options"];</code>
     */
    public Builder addOptions(
        int index, com.google.protobuf.Option.Builder builderForValue) {
      copyOnWrite();
      instance.addOptions(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Option options = 3 [json_name = "options"];</code>
     */
    public Builder addAllOptions(
        java.lang.Iterable<? extends com.google.protobuf.Option> values) {
      copyOnWrite();
      instance.addAllOptions(values);
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Option options = 3 [json_name = "options"];</code>
     */
    public Builder clearOptions() {
      copyOnWrite();
      instance.clearOptions();
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Option options = 3 [json_name = "options"];</code>
     */
    public Builder removeOptions(int index) {
      copyOnWrite();
      instance.removeOptions(index);
      return this;
    }

    /**
     * <code>.google.protobuf.SourceContext source_context = 4 [json_name = "sourceContext"];</code>
     */
    @java.lang.Override
    public boolean hasSourceContext() {
      return instance.hasSourceContext();
    }
    /**
     * <code>.google.protobuf.SourceContext source_context = 4 [json_name = "sourceContext"];</code>
     */
    @java.lang.Override
    public com.google.protobuf.SourceContext getSourceContext() {
      return instance.getSourceContext();
    }
    /**
     * <code>.google.protobuf.SourceContext source_context = 4 [json_name = "sourceContext"];</code>
     */
    public Builder setSourceContext(com.google.protobuf.SourceContext value) {
      copyOnWrite();
      instance.setSourceContext(value);
      return this;
      }
    /**
     * <code>.google.protobuf.SourceContext source_context = 4 [json_name = "sourceContext"];</code>
     */
    public Builder setSourceContext(
        com.google.protobuf.SourceContext.Builder builderForValue) {
      copyOnWrite();
      instance.setSourceContext(builderForValue.build());
      return this;
    }
    /**
     * <code>.google.protobuf.SourceContext source_context = 4 [json_name = "sourceContext"];</code>
     */
    public Builder mergeSourceContext(com.google.protobuf.SourceContext value) {
      copyOnWrite();
      instance.mergeSourceContext(value);
      return this;
    }
    /**
     * <code>.google.protobuf.SourceContext source_context = 4 [json_name = "sourceContext"];</code>
     */
    public Builder clearSourceContext() {  copyOnWrite();
      instance.clearSourceContext();
      return this;
    }

    /**
     * <code>.google.protobuf.Syntax syntax = 5 [json_name = "syntax"];</code>
     * @return The enum numeric value on the wire for syntax.
     */
    @java.lang.Override
    public int getSyntaxValue() {
      return instance.getSyntaxValue();
    }
    /**
     * <code>.google.protobuf.Syntax syntax = 5 [json_name = "syntax"];</code>
     * @param value The syntax to set.
     * @return This builder for chaining.
     */
    public Builder setSyntaxValue(int value) {
      copyOnWrite();
      instance.setSyntaxValue(value);
      return this;
    }
    /**
     * <code>.google.protobuf.Syntax syntax = 5 [json_name = "syntax"];</code>
     * @return The syntax.
     */
    @java.lang.Override
    public com.google.protobuf.Syntax getSyntax() {
      return instance.getSyntax();
    }
    /**
     * <code>.google.protobuf.Syntax syntax = 5 [json_name = "syntax"];</code>
     * @param value The enum numeric value on the wire for syntax to set.
     * @return This builder for chaining.
     */
    public Builder setSyntax(com.google.protobuf.Syntax value) {
      copyOnWrite();
      instance.setSyntax(value);
      return this;
    }
    /**
     * <code>.google.protobuf.Syntax syntax = 5 [json_name = "syntax"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSyntax() {
      copyOnWrite();
      instance.clearSyntax();
      return this;
    }

    /**
     * <code>string edition = 6 [json_name = "edition"];</code>
     * @return The edition.
     */
    @java.lang.Override
    public java.lang.String getEdition() {
      return instance.getEdition();
    }
    /**
     * <code>string edition = 6 [json_name = "edition"];</code>
     * @return The bytes for edition.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEditionBytes() {
      return instance.getEditionBytes();
    }
    /**
     * <code>string edition = 6 [json_name = "edition"];</code>
     * @param value The edition to set.
     * @return This builder for chaining.
     */
    public Builder setEdition(
        java.lang.String value) {
      copyOnWrite();
      instance.setEdition(value);
      return this;
    }
    /**
     * <code>string edition = 6 [json_name = "edition"];</code>
     * @return This builder for chaining.
     */
    public Builder clearEdition() {
      copyOnWrite();
      instance.clearEdition();
      return this;
    }
    /**
     * <code>string edition = 6 [json_name = "edition"];</code>
     * @param value The bytes for edition to set.
     * @return This builder for chaining.
     */
    public Builder setEditionBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setEditionBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:google.protobuf.Enum)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.google.protobuf.Enum();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "name_",
            "enumvalue_",
            com.google.protobuf.EnumValue.class,
            "options_",
            com.google.protobuf.Option.class,
            "sourceContext_",
            "syntax_",
            "edition_",
          };
          java.lang.String info =
              "\u0000\u0006\u0000\u0001\u0001\u0006\u0006\u0000\u0002\u0000\u0001\u0208\u0002\u001b" +
              "\u0003\u001b\u0004\u1009\u0000\u0005\f\u0006\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.google.protobuf.Enum> parser = PARSER;
        if (parser == null) {
          synchronized (com.google.protobuf.Enum.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.google.protobuf.Enum>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:google.protobuf.Enum)
  private static final com.google.protobuf.Enum DEFAULT_INSTANCE;
  static {
    Enum defaultInstance = new Enum();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Enum.class, defaultInstance);
  }

  public static com.google.protobuf.Enum getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Enum> PARSER;

  public static com.google.protobuf.Parser<Enum> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

