// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/protobuf/descriptor.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.google.protobuf;

@kotlin.jvm.JvmName("-initializeextensionRangeOptions")
public inline fun extensionRangeOptions(block: com.google.protobuf.ExtensionRangeOptionsKt.Dsl.() -> kotlin.Unit): com.google.protobuf.DescriptorProtos.ExtensionRangeOptions =
  com.google.protobuf.ExtensionRangeOptionsKt.Dsl._create(com.google.protobuf.DescriptorProtos.ExtensionRangeOptions.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `google.protobuf.ExtensionRangeOptions`
 */
public object ExtensionRangeOptionsKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.google.protobuf.DescriptorProtos.ExtensionRangeOptions.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.google.protobuf.DescriptorProtos.ExtensionRangeOptions.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.google.protobuf.DescriptorProtos.ExtensionRangeOptions = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class UninterpretedOptionProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999 [json_name = "uninterpretedOption"];`
     */
     public val uninterpretedOption: com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.UninterpretedOption, UninterpretedOptionProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.uninterpretedOptionList
      )
    /**
     * `repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999 [json_name = "uninterpretedOption"];`
     * @param value The uninterpretedOption to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addUninterpretedOption")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.UninterpretedOption, UninterpretedOptionProxy>.add(value: com.google.protobuf.DescriptorProtos.UninterpretedOption) {
      _builder.addUninterpretedOption(value)
    }
    /**
     * `repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999 [json_name = "uninterpretedOption"];`
     * @param value The uninterpretedOption to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignUninterpretedOption")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.UninterpretedOption, UninterpretedOptionProxy>.plusAssign(value: com.google.protobuf.DescriptorProtos.UninterpretedOption) {
      add(value)
    }
    /**
     * `repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999 [json_name = "uninterpretedOption"];`
     * @param values The uninterpretedOption to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllUninterpretedOption")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.UninterpretedOption, UninterpretedOptionProxy>.addAll(values: kotlin.collections.Iterable<com.google.protobuf.DescriptorProtos.UninterpretedOption>) {
      _builder.addAllUninterpretedOption(values)
    }
    /**
     * `repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999 [json_name = "uninterpretedOption"];`
     * @param values The uninterpretedOption to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllUninterpretedOption")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.UninterpretedOption, UninterpretedOptionProxy>.plusAssign(values: kotlin.collections.Iterable<com.google.protobuf.DescriptorProtos.UninterpretedOption>) {
      addAll(values)
    }
    /**
     * `repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999 [json_name = "uninterpretedOption"];`
     * @param index The index to set the value at.
     * @param value The uninterpretedOption to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setUninterpretedOption")
    public operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.UninterpretedOption, UninterpretedOptionProxy>.set(index: kotlin.Int, value: com.google.protobuf.DescriptorProtos.UninterpretedOption) {
      _builder.setUninterpretedOption(index, value)
    }
    /**
     * `repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999 [json_name = "uninterpretedOption"];`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearUninterpretedOption")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.UninterpretedOption, UninterpretedOptionProxy>.clear() {
      _builder.clearUninterpretedOption()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class DeclarationProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .google.protobuf.ExtensionRangeOptions.Declaration declaration = 2 [json_name = "declaration", retention = RETENTION_SOURCE];`
     */
     public val declaration: com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.ExtensionRangeOptions.Declaration, DeclarationProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.declarationList
      )
    /**
     * `repeated .google.protobuf.ExtensionRangeOptions.Declaration declaration = 2 [json_name = "declaration", retention = RETENTION_SOURCE];`
     * @param value The declaration to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addDeclaration")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.ExtensionRangeOptions.Declaration, DeclarationProxy>.add(value: com.google.protobuf.DescriptorProtos.ExtensionRangeOptions.Declaration) {
      _builder.addDeclaration(value)
    }
    /**
     * `repeated .google.protobuf.ExtensionRangeOptions.Declaration declaration = 2 [json_name = "declaration", retention = RETENTION_SOURCE];`
     * @param value The declaration to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignDeclaration")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.ExtensionRangeOptions.Declaration, DeclarationProxy>.plusAssign(value: com.google.protobuf.DescriptorProtos.ExtensionRangeOptions.Declaration) {
      add(value)
    }
    /**
     * `repeated .google.protobuf.ExtensionRangeOptions.Declaration declaration = 2 [json_name = "declaration", retention = RETENTION_SOURCE];`
     * @param values The declaration to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllDeclaration")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.ExtensionRangeOptions.Declaration, DeclarationProxy>.addAll(values: kotlin.collections.Iterable<com.google.protobuf.DescriptorProtos.ExtensionRangeOptions.Declaration>) {
      _builder.addAllDeclaration(values)
    }
    /**
     * `repeated .google.protobuf.ExtensionRangeOptions.Declaration declaration = 2 [json_name = "declaration", retention = RETENTION_SOURCE];`
     * @param values The declaration to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllDeclaration")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.ExtensionRangeOptions.Declaration, DeclarationProxy>.plusAssign(values: kotlin.collections.Iterable<com.google.protobuf.DescriptorProtos.ExtensionRangeOptions.Declaration>) {
      addAll(values)
    }
    /**
     * `repeated .google.protobuf.ExtensionRangeOptions.Declaration declaration = 2 [json_name = "declaration", retention = RETENTION_SOURCE];`
     * @param index The index to set the value at.
     * @param value The declaration to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setDeclaration")
    public operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.ExtensionRangeOptions.Declaration, DeclarationProxy>.set(index: kotlin.Int, value: com.google.protobuf.DescriptorProtos.ExtensionRangeOptions.Declaration) {
      _builder.setDeclaration(index, value)
    }
    /**
     * `repeated .google.protobuf.ExtensionRangeOptions.Declaration declaration = 2 [json_name = "declaration", retention = RETENTION_SOURCE];`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearDeclaration")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.ExtensionRangeOptions.Declaration, DeclarationProxy>.clear() {
      _builder.clearDeclaration()
    }

    /**
     * `optional .google.protobuf.FeatureSet features = 50 [json_name = "features"];`
     */
    public var features: com.google.protobuf.DescriptorProtos.FeatureSet
      @JvmName("getFeatures")
      get() = _builder.features
      @JvmName("setFeatures")
      set(value) {
        _builder.features = value
      }
    /**
     * `optional .google.protobuf.FeatureSet features = 50 [json_name = "features"];`
     */
    public fun clearFeatures() {
      _builder.clearFeatures()
    }
    /**
     * `optional .google.protobuf.FeatureSet features = 50 [json_name = "features"];`
     * @return Whether the features field is set.
     */
    public fun hasFeatures(): kotlin.Boolean {
      return _builder.hasFeatures()
    }
    public val ExtensionRangeOptionsKt.Dsl.featuresOrNull: com.google.protobuf.DescriptorProtos.FeatureSet?
      get() = _builder.featuresOrNull

    /**
     * `optional .google.protobuf.ExtensionRangeOptions.VerificationState verification = 3 [default = UNVERIFIED, json_name = "verification", retention = RETENTION_SOURCE];`
     */
    public var verification: com.google.protobuf.DescriptorProtos.ExtensionRangeOptions.VerificationState
      @JvmName("getVerification")
      get() = _builder.verification
      @JvmName("setVerification")
      set(value) {
        _builder.verification = value
      }
    /**
     * `optional .google.protobuf.ExtensionRangeOptions.VerificationState verification = 3 [default = UNVERIFIED, json_name = "verification", retention = RETENTION_SOURCE];`
     */
    public fun clearVerification() {
      _builder.clearVerification()
    }
    /**
     * `optional .google.protobuf.ExtensionRangeOptions.VerificationState verification = 3 [default = UNVERIFIED, json_name = "verification", retention = RETENTION_SOURCE];`
     * @return Whether the verification field is set.
     */
    public fun hasVerification(): kotlin.Boolean {
      return _builder.hasVerification()
    }
    @Suppress("UNCHECKED_CAST")
    @kotlin.jvm.JvmSynthetic
    public operator fun <T : kotlin.Any> get(extension: com.google.protobuf.ExtensionLite<com.google.protobuf.DescriptorProtos.ExtensionRangeOptions, T>): T {
      return if (extension.isRepeated) {
        get(extension as com.google.protobuf.ExtensionLite<com.google.protobuf.DescriptorProtos.ExtensionRangeOptions, kotlin.collections.List<*>>) as T
      } else {
        _builder.getExtension(extension)
      }
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @kotlin.jvm.JvmName("-getRepeatedExtension")
    public operator fun <E : kotlin.Any> get(
      extension: com.google.protobuf.ExtensionLite<com.google.protobuf.DescriptorProtos.ExtensionRangeOptions, kotlin.collections.List<E>>
    ): com.google.protobuf.kotlin.ExtensionList<E, com.google.protobuf.DescriptorProtos.ExtensionRangeOptions> {
      return com.google.protobuf.kotlin.ExtensionList(extension, _builder.getExtension(extension))
    }

    @kotlin.jvm.JvmSynthetic
    public operator fun contains(extension: com.google.protobuf.ExtensionLite<com.google.protobuf.DescriptorProtos.ExtensionRangeOptions, *>): Boolean {
      return _builder.hasExtension(extension)
    }

    @kotlin.jvm.JvmSynthetic
    public fun clear(extension: com.google.protobuf.ExtensionLite<com.google.protobuf.DescriptorProtos.ExtensionRangeOptions, *>) {
      _builder.clearExtension(extension)
    }

    @kotlin.jvm.JvmSynthetic
    public fun <T : kotlin.Any> setExtension(extension: com.google.protobuf.ExtensionLite<com.google.protobuf.DescriptorProtos.ExtensionRangeOptions, T>, value: T) {
      _builder.setExtension(extension, value)
    }

    @kotlin.jvm.JvmSynthetic
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun <T : Comparable<T>> set(
      extension: com.google.protobuf.ExtensionLite<com.google.protobuf.DescriptorProtos.ExtensionRangeOptions, T>,
      value: T
    ) {
      setExtension(extension, value)
    }

    @kotlin.jvm.JvmSynthetic
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun set(
      extension: com.google.protobuf.ExtensionLite<com.google.protobuf.DescriptorProtos.ExtensionRangeOptions, com.google.protobuf.ByteString>,
      value: com.google.protobuf.ByteString
    ) {
      setExtension(extension, value)
    }

    @kotlin.jvm.JvmSynthetic
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun <T : com.google.protobuf.MessageLite> set(
      extension: com.google.protobuf.ExtensionLite<com.google.protobuf.DescriptorProtos.ExtensionRangeOptions, T>,
      value: T
    ) {
      setExtension(extension, value)
    }

    @kotlin.jvm.JvmSynthetic
    public fun<E : kotlin.Any> com.google.protobuf.kotlin.ExtensionList<E, com.google.protobuf.DescriptorProtos.ExtensionRangeOptions>.add(value: E) {
      _builder.addExtension(this.extension, value)
    }

    @kotlin.jvm.JvmSynthetic
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun <E : kotlin.Any> com.google.protobuf.kotlin.ExtensionList<E, com.google.protobuf.DescriptorProtos.ExtensionRangeOptions>.plusAssign(value: E) {
      add(value)
    }

    @kotlin.jvm.JvmSynthetic
    public fun<E : kotlin.Any> com.google.protobuf.kotlin.ExtensionList<E, com.google.protobuf.DescriptorProtos.ExtensionRangeOptions>.addAll(values: Iterable<E>) {
      for (value in values) {
        add(value)
      }
    }

    @kotlin.jvm.JvmSynthetic
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun <E : kotlin.Any> com.google.protobuf.kotlin.ExtensionList<E, com.google.protobuf.DescriptorProtos.ExtensionRangeOptions>.plusAssign(values: Iterable<E>) {
      addAll(values)
    }

    @kotlin.jvm.JvmSynthetic
    public operator fun <E : kotlin.Any> com.google.protobuf.kotlin.ExtensionList<E, com.google.protobuf.DescriptorProtos.ExtensionRangeOptions>.set(index: Int, value: E) {
      _builder.setExtension(this.extension, index, value)
    }

    @kotlin.jvm.JvmSynthetic
    @Suppress("NOTHING_TO_INLINE")
    public inline fun com.google.protobuf.kotlin.ExtensionList<*, com.google.protobuf.DescriptorProtos.ExtensionRangeOptions>.clear() {
      clear(extension)
    }

  }
  @kotlin.jvm.JvmName("-initializedeclaration")
  public inline fun declaration(block: com.google.protobuf.ExtensionRangeOptionsKt.DeclarationKt.Dsl.() -> kotlin.Unit): com.google.protobuf.DescriptorProtos.ExtensionRangeOptions.Declaration =
    com.google.protobuf.ExtensionRangeOptionsKt.DeclarationKt.Dsl._create(com.google.protobuf.DescriptorProtos.ExtensionRangeOptions.Declaration.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `google.protobuf.ExtensionRangeOptions.Declaration`
   */
  public object DeclarationKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: com.google.protobuf.DescriptorProtos.ExtensionRangeOptions.Declaration.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _create(builder: com.google.protobuf.DescriptorProtos.ExtensionRangeOptions.Declaration.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _build(): com.google.protobuf.DescriptorProtos.ExtensionRangeOptions.Declaration = _builder.build()

      /**
       * <code>optional int32 number = 1 [json_name = "number"];</code>
       */
      public var number: kotlin.Int
        @JvmName("getNumber")
        get() = _builder.number
        @JvmName("setNumber")
        set(value) {
          _builder.number = value
        }
      /**
       * `optional int32 number = 1 [json_name = "number"];`
       */
      public fun clearNumber() {
        _builder.clearNumber()
      }
      /**
       * `optional int32 number = 1 [json_name = "number"];`
       * @return Whether the number field is set.
       */
      public fun hasNumber(): kotlin.Boolean {
        return _builder.hasNumber()
      }

      /**
       * `optional string full_name = 2 [json_name = "fullName"];`
       */
      public var fullName: kotlin.String
        @JvmName("getFullName")
        get() = _builder.fullName
        @JvmName("setFullName")
        set(value) {
          _builder.fullName = value
        }
      /**
       * `optional string full_name = 2 [json_name = "fullName"];`
       */
      public fun clearFullName() {
        _builder.clearFullName()
      }
      /**
       * `optional string full_name = 2 [json_name = "fullName"];`
       * @return Whether the fullName field is set.
       */
      public fun hasFullName(): kotlin.Boolean {
        return _builder.hasFullName()
      }

      /**
       * `optional string type = 3 [json_name = "type"];`
       */
      public var type: kotlin.String
        @JvmName("getType")
        get() = _builder.type
        @JvmName("setType")
        set(value) {
          _builder.type = value
        }
      /**
       * `optional string type = 3 [json_name = "type"];`
       */
      public fun clearType() {
        _builder.clearType()
      }
      /**
       * `optional string type = 3 [json_name = "type"];`
       * @return Whether the type field is set.
       */
      public fun hasType(): kotlin.Boolean {
        return _builder.hasType()
      }

      /**
       * <code>optional bool reserved = 5 [json_name = "reserved"];</code>
       */
      public var reserved: kotlin.Boolean
        @JvmName("getReserved")
        get() = _builder.reserved
        @JvmName("setReserved")
        set(value) {
          _builder.reserved = value
        }
      /**
       * `optional bool reserved = 5 [json_name = "reserved"];`
       */
      public fun clearReserved() {
        _builder.clearReserved()
      }
      /**
       * `optional bool reserved = 5 [json_name = "reserved"];`
       * @return Whether the reserved field is set.
       */
      public fun hasReserved(): kotlin.Boolean {
        return _builder.hasReserved()
      }

      /**
       * <code>optional bool repeated = 6 [json_name = "repeated"];</code>
       */
      public var repeated: kotlin.Boolean
        @JvmName("getRepeated")
        get() = _builder.repeated
        @JvmName("setRepeated")
        set(value) {
          _builder.repeated = value
        }
      /**
       * `optional bool repeated = 6 [json_name = "repeated"];`
       */
      public fun clearRepeated() {
        _builder.clearRepeated()
      }
      /**
       * `optional bool repeated = 6 [json_name = "repeated"];`
       * @return Whether the repeated field is set.
       */
      public fun hasRepeated(): kotlin.Boolean {
        return _builder.hasRepeated()
      }
    }
  }
}
public inline fun com.google.protobuf.DescriptorProtos.ExtensionRangeOptions.copy(block: `com.google.protobuf`.ExtensionRangeOptionsKt.Dsl.() -> kotlin.Unit): com.google.protobuf.DescriptorProtos.ExtensionRangeOptions =
  `com.google.protobuf`.ExtensionRangeOptionsKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public inline fun com.google.protobuf.DescriptorProtos.ExtensionRangeOptions.Declaration.copy(block: `com.google.protobuf`.ExtensionRangeOptionsKt.DeclarationKt.Dsl.() -> kotlin.Unit): com.google.protobuf.DescriptorProtos.ExtensionRangeOptions.Declaration =
  `com.google.protobuf`.ExtensionRangeOptionsKt.DeclarationKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.google.protobuf.DescriptorProtos.ExtensionRangeOptionsOrBuilder.featuresOrNull: com.google.protobuf.DescriptorProtos.FeatureSet?
  get() = if (hasFeatures()) getFeatures() else null

