// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/protobuf/descriptor.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.google.protobuf;

@kotlin.jvm.JvmName("-initializefeatureSetDefaults")
public inline fun featureSetDefaults(block: com.google.protobuf.FeatureSetDefaultsKt.Dsl.() -> kotlin.Unit): com.google.protobuf.DescriptorProtos.FeatureSetDefaults =
  com.google.protobuf.FeatureSetDefaultsKt.Dsl._create(com.google.protobuf.DescriptorProtos.FeatureSetDefaults.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `google.protobuf.FeatureSetDefaults`
 */
public object FeatureSetDefaultsKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.google.protobuf.DescriptorProtos.FeatureSetDefaults.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.google.protobuf.DescriptorProtos.FeatureSetDefaults.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.google.protobuf.DescriptorProtos.FeatureSetDefaults = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class DefaultsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .google.protobuf.FeatureSetDefaults.FeatureSetEditionDefault defaults = 1 [json_name = "defaults"];`
     */
     public val defaults: com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.FeatureSetDefaults.FeatureSetEditionDefault, DefaultsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.defaultsList
      )
    /**
     * `repeated .google.protobuf.FeatureSetDefaults.FeatureSetEditionDefault defaults = 1 [json_name = "defaults"];`
     * @param value The defaults to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addDefaults")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.FeatureSetDefaults.FeatureSetEditionDefault, DefaultsProxy>.add(value: com.google.protobuf.DescriptorProtos.FeatureSetDefaults.FeatureSetEditionDefault) {
      _builder.addDefaults(value)
    }
    /**
     * `repeated .google.protobuf.FeatureSetDefaults.FeatureSetEditionDefault defaults = 1 [json_name = "defaults"];`
     * @param value The defaults to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignDefaults")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.FeatureSetDefaults.FeatureSetEditionDefault, DefaultsProxy>.plusAssign(value: com.google.protobuf.DescriptorProtos.FeatureSetDefaults.FeatureSetEditionDefault) {
      add(value)
    }
    /**
     * `repeated .google.protobuf.FeatureSetDefaults.FeatureSetEditionDefault defaults = 1 [json_name = "defaults"];`
     * @param values The defaults to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllDefaults")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.FeatureSetDefaults.FeatureSetEditionDefault, DefaultsProxy>.addAll(values: kotlin.collections.Iterable<com.google.protobuf.DescriptorProtos.FeatureSetDefaults.FeatureSetEditionDefault>) {
      _builder.addAllDefaults(values)
    }
    /**
     * `repeated .google.protobuf.FeatureSetDefaults.FeatureSetEditionDefault defaults = 1 [json_name = "defaults"];`
     * @param values The defaults to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllDefaults")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.FeatureSetDefaults.FeatureSetEditionDefault, DefaultsProxy>.plusAssign(values: kotlin.collections.Iterable<com.google.protobuf.DescriptorProtos.FeatureSetDefaults.FeatureSetEditionDefault>) {
      addAll(values)
    }
    /**
     * `repeated .google.protobuf.FeatureSetDefaults.FeatureSetEditionDefault defaults = 1 [json_name = "defaults"];`
     * @param index The index to set the value at.
     * @param value The defaults to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setDefaults")
    public operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.FeatureSetDefaults.FeatureSetEditionDefault, DefaultsProxy>.set(index: kotlin.Int, value: com.google.protobuf.DescriptorProtos.FeatureSetDefaults.FeatureSetEditionDefault) {
      _builder.setDefaults(index, value)
    }
    /**
     * `repeated .google.protobuf.FeatureSetDefaults.FeatureSetEditionDefault defaults = 1 [json_name = "defaults"];`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearDefaults")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.FeatureSetDefaults.FeatureSetEditionDefault, DefaultsProxy>.clear() {
      _builder.clearDefaults()
    }

    /**
     * `optional .google.protobuf.Edition minimum_edition = 4 [json_name = "minimumEdition"];`
     */
    public var minimumEdition: com.google.protobuf.DescriptorProtos.Edition
      @JvmName("getMinimumEdition")
      get() = _builder.minimumEdition
      @JvmName("setMinimumEdition")
      set(value) {
        _builder.minimumEdition = value
      }
    /**
     * `optional .google.protobuf.Edition minimum_edition = 4 [json_name = "minimumEdition"];`
     */
    public fun clearMinimumEdition() {
      _builder.clearMinimumEdition()
    }
    /**
     * `optional .google.protobuf.Edition minimum_edition = 4 [json_name = "minimumEdition"];`
     * @return Whether the minimumEdition field is set.
     */
    public fun hasMinimumEdition(): kotlin.Boolean {
      return _builder.hasMinimumEdition()
    }

    /**
     * `optional .google.protobuf.Edition maximum_edition = 5 [json_name = "maximumEdition"];`
     */
    public var maximumEdition: com.google.protobuf.DescriptorProtos.Edition
      @JvmName("getMaximumEdition")
      get() = _builder.maximumEdition
      @JvmName("setMaximumEdition")
      set(value) {
        _builder.maximumEdition = value
      }
    /**
     * `optional .google.protobuf.Edition maximum_edition = 5 [json_name = "maximumEdition"];`
     */
    public fun clearMaximumEdition() {
      _builder.clearMaximumEdition()
    }
    /**
     * `optional .google.protobuf.Edition maximum_edition = 5 [json_name = "maximumEdition"];`
     * @return Whether the maximumEdition field is set.
     */
    public fun hasMaximumEdition(): kotlin.Boolean {
      return _builder.hasMaximumEdition()
    }
  }
  @kotlin.jvm.JvmName("-initializefeatureSetEditionDefault")
  public inline fun featureSetEditionDefault(block: com.google.protobuf.FeatureSetDefaultsKt.FeatureSetEditionDefaultKt.Dsl.() -> kotlin.Unit): com.google.protobuf.DescriptorProtos.FeatureSetDefaults.FeatureSetEditionDefault =
    com.google.protobuf.FeatureSetDefaultsKt.FeatureSetEditionDefaultKt.Dsl._create(com.google.protobuf.DescriptorProtos.FeatureSetDefaults.FeatureSetEditionDefault.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `google.protobuf.FeatureSetDefaults.FeatureSetEditionDefault`
   */
  public object FeatureSetEditionDefaultKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: com.google.protobuf.DescriptorProtos.FeatureSetDefaults.FeatureSetEditionDefault.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _create(builder: com.google.protobuf.DescriptorProtos.FeatureSetDefaults.FeatureSetEditionDefault.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _build(): com.google.protobuf.DescriptorProtos.FeatureSetDefaults.FeatureSetEditionDefault = _builder.build()

      /**
       * `optional .google.protobuf.Edition edition = 3 [json_name = "edition"];`
       */
      public var edition: com.google.protobuf.DescriptorProtos.Edition
        @JvmName("getEdition")
        get() = _builder.edition
        @JvmName("setEdition")
        set(value) {
          _builder.edition = value
        }
      /**
       * `optional .google.protobuf.Edition edition = 3 [json_name = "edition"];`
       */
      public fun clearEdition() {
        _builder.clearEdition()
      }
      /**
       * `optional .google.protobuf.Edition edition = 3 [json_name = "edition"];`
       * @return Whether the edition field is set.
       */
      public fun hasEdition(): kotlin.Boolean {
        return _builder.hasEdition()
      }

      /**
       * `optional .google.protobuf.FeatureSet overridable_features = 4 [json_name = "overridableFeatures"];`
       */
      public var overridableFeatures: com.google.protobuf.DescriptorProtos.FeatureSet
        @JvmName("getOverridableFeatures")
        get() = _builder.overridableFeatures
        @JvmName("setOverridableFeatures")
        set(value) {
          _builder.overridableFeatures = value
        }
      /**
       * `optional .google.protobuf.FeatureSet overridable_features = 4 [json_name = "overridableFeatures"];`
       */
      public fun clearOverridableFeatures() {
        _builder.clearOverridableFeatures()
      }
      /**
       * `optional .google.protobuf.FeatureSet overridable_features = 4 [json_name = "overridableFeatures"];`
       * @return Whether the overridableFeatures field is set.
       */
      public fun hasOverridableFeatures(): kotlin.Boolean {
        return _builder.hasOverridableFeatures()
      }
      public val FeatureSetEditionDefaultKt.Dsl.overridableFeaturesOrNull: com.google.protobuf.DescriptorProtos.FeatureSet?
        get() = _builder.overridableFeaturesOrNull

      /**
       * `optional .google.protobuf.FeatureSet fixed_features = 5 [json_name = "fixedFeatures"];`
       */
      public var fixedFeatures: com.google.protobuf.DescriptorProtos.FeatureSet
        @JvmName("getFixedFeatures")
        get() = _builder.fixedFeatures
        @JvmName("setFixedFeatures")
        set(value) {
          _builder.fixedFeatures = value
        }
      /**
       * `optional .google.protobuf.FeatureSet fixed_features = 5 [json_name = "fixedFeatures"];`
       */
      public fun clearFixedFeatures() {
        _builder.clearFixedFeatures()
      }
      /**
       * `optional .google.protobuf.FeatureSet fixed_features = 5 [json_name = "fixedFeatures"];`
       * @return Whether the fixedFeatures field is set.
       */
      public fun hasFixedFeatures(): kotlin.Boolean {
        return _builder.hasFixedFeatures()
      }
      public val FeatureSetEditionDefaultKt.Dsl.fixedFeaturesOrNull: com.google.protobuf.DescriptorProtos.FeatureSet?
        get() = _builder.fixedFeaturesOrNull
    }
  }
}
public inline fun com.google.protobuf.DescriptorProtos.FeatureSetDefaults.copy(block: `com.google.protobuf`.FeatureSetDefaultsKt.Dsl.() -> kotlin.Unit): com.google.protobuf.DescriptorProtos.FeatureSetDefaults =
  `com.google.protobuf`.FeatureSetDefaultsKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public inline fun com.google.protobuf.DescriptorProtos.FeatureSetDefaults.FeatureSetEditionDefault.copy(block: `com.google.protobuf`.FeatureSetDefaultsKt.FeatureSetEditionDefaultKt.Dsl.() -> kotlin.Unit): com.google.protobuf.DescriptorProtos.FeatureSetDefaults.FeatureSetEditionDefault =
  `com.google.protobuf`.FeatureSetDefaultsKt.FeatureSetEditionDefaultKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.google.protobuf.DescriptorProtos.FeatureSetDefaults.FeatureSetEditionDefaultOrBuilder.overridableFeaturesOrNull: com.google.protobuf.DescriptorProtos.FeatureSet?
  get() = if (hasOverridableFeatures()) getOverridableFeatures() else null

public val com.google.protobuf.DescriptorProtos.FeatureSetDefaults.FeatureSetEditionDefaultOrBuilder.fixedFeaturesOrNull: com.google.protobuf.DescriptorProtos.FeatureSet?
  get() = if (hasFixedFeatures()) getFixedFeatures() else null

