// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/protobuf/descriptor.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.google.protobuf;

@kotlin.jvm.JvmName("-initializefieldDescriptorProto")
public inline fun fieldDescriptorProto(block: com.google.protobuf.FieldDescriptorProtoKt.Dsl.() -> kotlin.Unit): com.google.protobuf.DescriptorProtos.FieldDescriptorProto =
  com.google.protobuf.FieldDescriptorProtoKt.Dsl._create(com.google.protobuf.DescriptorProtos.FieldDescriptorProto.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `google.protobuf.FieldDescriptorProto`
 */
public object FieldDescriptorProtoKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.google.protobuf.DescriptorProtos.FieldDescriptorProto.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.google.protobuf.DescriptorProtos.FieldDescriptorProto.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.google.protobuf.DescriptorProtos.FieldDescriptorProto = _builder.build()

    /**
     * `optional string name = 1 [json_name = "name"];`
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.name
      @JvmName("setName")
      set(value) {
        _builder.name = value
      }
    /**
     * `optional string name = 1 [json_name = "name"];`
     */
    public fun clearName() {
      _builder.clearName()
    }
    /**
     * `optional string name = 1 [json_name = "name"];`
     * @return Whether the name field is set.
     */
    public fun hasName(): kotlin.Boolean {
      return _builder.hasName()
    }

    /**
     * <code>optional int32 number = 3 [json_name = "number"];</code>
     */
    public var number: kotlin.Int
      @JvmName("getNumber")
      get() = _builder.number
      @JvmName("setNumber")
      set(value) {
        _builder.number = value
      }
    /**
     * `optional int32 number = 3 [json_name = "number"];`
     */
    public fun clearNumber() {
      _builder.clearNumber()
    }
    /**
     * `optional int32 number = 3 [json_name = "number"];`
     * @return Whether the number field is set.
     */
    public fun hasNumber(): kotlin.Boolean {
      return _builder.hasNumber()
    }

    /**
     * `optional .google.protobuf.FieldDescriptorProto.Label label = 4 [json_name = "label"];`
     */
    public var label: com.google.protobuf.DescriptorProtos.FieldDescriptorProto.Label
      @JvmName("getLabel")
      get() = _builder.label
      @JvmName("setLabel")
      set(value) {
        _builder.label = value
      }
    /**
     * `optional .google.protobuf.FieldDescriptorProto.Label label = 4 [json_name = "label"];`
     */
    public fun clearLabel() {
      _builder.clearLabel()
    }
    /**
     * `optional .google.protobuf.FieldDescriptorProto.Label label = 4 [json_name = "label"];`
     * @return Whether the label field is set.
     */
    public fun hasLabel(): kotlin.Boolean {
      return _builder.hasLabel()
    }

    /**
     * `optional .google.protobuf.FieldDescriptorProto.Type type = 5 [json_name = "type"];`
     */
    public var type: com.google.protobuf.DescriptorProtos.FieldDescriptorProto.Type
      @JvmName("getType")
      get() = _builder.type
      @JvmName("setType")
      set(value) {
        _builder.type = value
      }
    /**
     * `optional .google.protobuf.FieldDescriptorProto.Type type = 5 [json_name = "type"];`
     */
    public fun clearType() {
      _builder.clearType()
    }
    /**
     * `optional .google.protobuf.FieldDescriptorProto.Type type = 5 [json_name = "type"];`
     * @return Whether the type field is set.
     */
    public fun hasType(): kotlin.Boolean {
      return _builder.hasType()
    }

    /**
     * `optional string type_name = 6 [json_name = "typeName"];`
     */
    public var typeName: kotlin.String
      @JvmName("getTypeName")
      get() = _builder.typeName
      @JvmName("setTypeName")
      set(value) {
        _builder.typeName = value
      }
    /**
     * `optional string type_name = 6 [json_name = "typeName"];`
     */
    public fun clearTypeName() {
      _builder.clearTypeName()
    }
    /**
     * `optional string type_name = 6 [json_name = "typeName"];`
     * @return Whether the typeName field is set.
     */
    public fun hasTypeName(): kotlin.Boolean {
      return _builder.hasTypeName()
    }

    /**
     * `optional string extendee = 2 [json_name = "extendee"];`
     */
    public var extendee: kotlin.String
      @JvmName("getExtendee")
      get() = _builder.extendee
      @JvmName("setExtendee")
      set(value) {
        _builder.extendee = value
      }
    /**
     * `optional string extendee = 2 [json_name = "extendee"];`
     */
    public fun clearExtendee() {
      _builder.clearExtendee()
    }
    /**
     * `optional string extendee = 2 [json_name = "extendee"];`
     * @return Whether the extendee field is set.
     */
    public fun hasExtendee(): kotlin.Boolean {
      return _builder.hasExtendee()
    }

    /**
     * `optional string default_value = 7 [json_name = "defaultValue"];`
     */
    public var defaultValue: kotlin.String
      @JvmName("getDefaultValue")
      get() = _builder.defaultValue
      @JvmName("setDefaultValue")
      set(value) {
        _builder.defaultValue = value
      }
    /**
     * `optional string default_value = 7 [json_name = "defaultValue"];`
     */
    public fun clearDefaultValue() {
      _builder.clearDefaultValue()
    }
    /**
     * `optional string default_value = 7 [json_name = "defaultValue"];`
     * @return Whether the defaultValue field is set.
     */
    public fun hasDefaultValue(): kotlin.Boolean {
      return _builder.hasDefaultValue()
    }

    /**
     * <code>optional int32 oneof_index = 9 [json_name = "oneofIndex"];</code>
     */
    public var oneofIndex: kotlin.Int
      @JvmName("getOneofIndex")
      get() = _builder.oneofIndex
      @JvmName("setOneofIndex")
      set(value) {
        _builder.oneofIndex = value
      }
    /**
     * `optional int32 oneof_index = 9 [json_name = "oneofIndex"];`
     */
    public fun clearOneofIndex() {
      _builder.clearOneofIndex()
    }
    /**
     * `optional int32 oneof_index = 9 [json_name = "oneofIndex"];`
     * @return Whether the oneofIndex field is set.
     */
    public fun hasOneofIndex(): kotlin.Boolean {
      return _builder.hasOneofIndex()
    }

    /**
     * `optional string json_name = 10 [json_name = "jsonName"];`
     */
    public var jsonName: kotlin.String
      @JvmName("getJsonName")
      get() = _builder.jsonName
      @JvmName("setJsonName")
      set(value) {
        _builder.jsonName = value
      }
    /**
     * `optional string json_name = 10 [json_name = "jsonName"];`
     */
    public fun clearJsonName() {
      _builder.clearJsonName()
    }
    /**
     * `optional string json_name = 10 [json_name = "jsonName"];`
     * @return Whether the jsonName field is set.
     */
    public fun hasJsonName(): kotlin.Boolean {
      return _builder.hasJsonName()
    }

    /**
     * `optional .google.protobuf.FieldOptions options = 8 [json_name = "options"];`
     */
    public var options: com.google.protobuf.DescriptorProtos.FieldOptions
      @JvmName("getOptions")
      get() = _builder.options
      @JvmName("setOptions")
      set(value) {
        _builder.options = value
      }
    /**
     * `optional .google.protobuf.FieldOptions options = 8 [json_name = "options"];`
     */
    public fun clearOptions() {
      _builder.clearOptions()
    }
    /**
     * `optional .google.protobuf.FieldOptions options = 8 [json_name = "options"];`
     * @return Whether the options field is set.
     */
    public fun hasOptions(): kotlin.Boolean {
      return _builder.hasOptions()
    }
    public val FieldDescriptorProtoKt.Dsl.optionsOrNull: com.google.protobuf.DescriptorProtos.FieldOptions?
      get() = _builder.optionsOrNull

    /**
     * <code>optional bool proto3_optional = 17 [json_name = "proto3Optional"];</code>
     */
    public var proto3Optional: kotlin.Boolean
      @JvmName("getProto3Optional")
      get() = _builder.proto3Optional
      @JvmName("setProto3Optional")
      set(value) {
        _builder.proto3Optional = value
      }
    /**
     * `optional bool proto3_optional = 17 [json_name = "proto3Optional"];`
     */
    public fun clearProto3Optional() {
      _builder.clearProto3Optional()
    }
    /**
     * `optional bool proto3_optional = 17 [json_name = "proto3Optional"];`
     * @return Whether the proto3Optional field is set.
     */
    public fun hasProto3Optional(): kotlin.Boolean {
      return _builder.hasProto3Optional()
    }
  }
}
public inline fun com.google.protobuf.DescriptorProtos.FieldDescriptorProto.copy(block: `com.google.protobuf`.FieldDescriptorProtoKt.Dsl.() -> kotlin.Unit): com.google.protobuf.DescriptorProtos.FieldDescriptorProto =
  `com.google.protobuf`.FieldDescriptorProtoKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.google.protobuf.DescriptorProtos.FieldDescriptorProtoOrBuilder.optionsOrNull: com.google.protobuf.DescriptorProtos.FieldOptions?
  get() = if (hasOptions()) getOptions() else null

