// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/protobuf/descriptor.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.google.protobuf;

@kotlin.jvm.JvmName("-initializefileDescriptorProto")
public inline fun fileDescriptorProto(block: com.google.protobuf.FileDescriptorProtoKt.Dsl.() -> kotlin.Unit): com.google.protobuf.DescriptorProtos.FileDescriptorProto =
  com.google.protobuf.FileDescriptorProtoKt.Dsl._create(com.google.protobuf.DescriptorProtos.FileDescriptorProto.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `google.protobuf.FileDescriptorProto`
 */
public object FileDescriptorProtoKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.google.protobuf.DescriptorProtos.FileDescriptorProto.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.google.protobuf.DescriptorProtos.FileDescriptorProto.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.google.protobuf.DescriptorProtos.FileDescriptorProto = _builder.build()

    /**
     * `optional string name = 1 [json_name = "name"];`
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.name
      @JvmName("setName")
      set(value) {
        _builder.name = value
      }
    /**
     * `optional string name = 1 [json_name = "name"];`
     */
    public fun clearName() {
      _builder.clearName()
    }
    /**
     * `optional string name = 1 [json_name = "name"];`
     * @return Whether the name field is set.
     */
    public fun hasName(): kotlin.Boolean {
      return _builder.hasName()
    }

    /**
     * `optional string package = 2 [json_name = "package"];`
     */
    public var package_: kotlin.String
      @JvmName("getPackage_")
      get() = _builder.`package`
      @JvmName("setPackage_")
      set(value) {
        _builder.`package` = value
      }
    /**
     * `optional string package = 2 [json_name = "package"];`
     */
    public fun clearPackage_() {
      _builder.clearPackage()
    }
    /**
     * `optional string package = 2 [json_name = "package"];`
     * @return Whether the package field is set.
     */
    public fun hasPackage_(): kotlin.Boolean {
      return _builder.hasPackage()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class DependencyProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated string dependency = 3 [json_name = "dependency"];`
     * @return A list containing the dependency.
     */
    public val dependency: com.google.protobuf.kotlin.DslList<kotlin.String, DependencyProxy>
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      get() = com.google.protobuf.kotlin.DslList(
        _builder.dependencyList
      )
    /**
     * `repeated string dependency = 3 [json_name = "dependency"];`
     * @param value The dependency to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addDependency")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, DependencyProxy>.add(value: kotlin.String) {
      _builder.addDependency(value)
    }
    /**
     * `repeated string dependency = 3 [json_name = "dependency"];`
     * @param value The dependency to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignDependency")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, DependencyProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * `repeated string dependency = 3 [json_name = "dependency"];`
     * @param values The dependency to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllDependency")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, DependencyProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllDependency(values)
    }
    /**
     * `repeated string dependency = 3 [json_name = "dependency"];`
     * @param values The dependency to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllDependency")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, DependencyProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * `repeated string dependency = 3 [json_name = "dependency"];`
     * @param index The index to set the value at.
     * @param value The dependency to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setDependency")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, DependencyProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setDependency(index, value)
    }/**
     * `repeated string dependency = 3 [json_name = "dependency"];`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearDependency")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, DependencyProxy>.clear() {
      _builder.clearDependency()
    }
    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class PublicDependencyProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated int32 public_dependency = 10 [json_name = "publicDependency"];</code>
     */
     public val publicDependency: com.google.protobuf.kotlin.DslList<kotlin.Int, PublicDependencyProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.publicDependencyList
      )
    /**
     * `repeated int32 public_dependency = 10 [json_name = "publicDependency"];`
     * @param value The publicDependency to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addPublicDependency")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Int, PublicDependencyProxy>.add(value: kotlin.Int) {
      _builder.addPublicDependency(value)
    }/**
     * `repeated int32 public_dependency = 10 [json_name = "publicDependency"];`
     * @param value The publicDependency to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignPublicDependency")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Int, PublicDependencyProxy>.plusAssign(value: kotlin.Int) {
      add(value)
    }/**
     * `repeated int32 public_dependency = 10 [json_name = "publicDependency"];`
     * @param values The publicDependency to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllPublicDependency")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Int, PublicDependencyProxy>.addAll(values: kotlin.collections.Iterable<kotlin.Int>) {
      _builder.addAllPublicDependency(values)
    }/**
     * `repeated int32 public_dependency = 10 [json_name = "publicDependency"];`
     * @param values The publicDependency to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllPublicDependency")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Int, PublicDependencyProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.Int>) {
      addAll(values)
    }/**
     * `repeated int32 public_dependency = 10 [json_name = "publicDependency"];`
     * @param index The index to set the value at.
     * @param value The publicDependency to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setPublicDependency")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.Int, PublicDependencyProxy>.set(index: kotlin.Int, value: kotlin.Int) {
      _builder.setPublicDependency(index, value)
    }/**
     * `repeated int32 public_dependency = 10 [json_name = "publicDependency"];`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearPublicDependency")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Int, PublicDependencyProxy>.clear() {
      _builder.clearPublicDependency()
    }
    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class WeakDependencyProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated int32 weak_dependency = 11 [json_name = "weakDependency"];</code>
     */
     public val weakDependency: com.google.protobuf.kotlin.DslList<kotlin.Int, WeakDependencyProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.weakDependencyList
      )
    /**
     * `repeated int32 weak_dependency = 11 [json_name = "weakDependency"];`
     * @param value The weakDependency to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addWeakDependency")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Int, WeakDependencyProxy>.add(value: kotlin.Int) {
      _builder.addWeakDependency(value)
    }/**
     * `repeated int32 weak_dependency = 11 [json_name = "weakDependency"];`
     * @param value The weakDependency to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignWeakDependency")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Int, WeakDependencyProxy>.plusAssign(value: kotlin.Int) {
      add(value)
    }/**
     * `repeated int32 weak_dependency = 11 [json_name = "weakDependency"];`
     * @param values The weakDependency to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllWeakDependency")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Int, WeakDependencyProxy>.addAll(values: kotlin.collections.Iterable<kotlin.Int>) {
      _builder.addAllWeakDependency(values)
    }/**
     * `repeated int32 weak_dependency = 11 [json_name = "weakDependency"];`
     * @param values The weakDependency to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllWeakDependency")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Int, WeakDependencyProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.Int>) {
      addAll(values)
    }/**
     * `repeated int32 weak_dependency = 11 [json_name = "weakDependency"];`
     * @param index The index to set the value at.
     * @param value The weakDependency to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setWeakDependency")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.Int, WeakDependencyProxy>.set(index: kotlin.Int, value: kotlin.Int) {
      _builder.setWeakDependency(index, value)
    }/**
     * `repeated int32 weak_dependency = 11 [json_name = "weakDependency"];`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearWeakDependency")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Int, WeakDependencyProxy>.clear() {
      _builder.clearWeakDependency()
    }
    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class MessageTypeProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .google.protobuf.DescriptorProto message_type = 4 [json_name = "messageType"];`
     */
     public val messageType: com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.DescriptorProto, MessageTypeProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.messageTypeList
      )
    /**
     * `repeated .google.protobuf.DescriptorProto message_type = 4 [json_name = "messageType"];`
     * @param value The messageType to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addMessageType")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.DescriptorProto, MessageTypeProxy>.add(value: com.google.protobuf.DescriptorProtos.DescriptorProto) {
      _builder.addMessageType(value)
    }
    /**
     * `repeated .google.protobuf.DescriptorProto message_type = 4 [json_name = "messageType"];`
     * @param value The messageType to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignMessageType")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.DescriptorProto, MessageTypeProxy>.plusAssign(value: com.google.protobuf.DescriptorProtos.DescriptorProto) {
      add(value)
    }
    /**
     * `repeated .google.protobuf.DescriptorProto message_type = 4 [json_name = "messageType"];`
     * @param values The messageType to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllMessageType")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.DescriptorProto, MessageTypeProxy>.addAll(values: kotlin.collections.Iterable<com.google.protobuf.DescriptorProtos.DescriptorProto>) {
      _builder.addAllMessageType(values)
    }
    /**
     * `repeated .google.protobuf.DescriptorProto message_type = 4 [json_name = "messageType"];`
     * @param values The messageType to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllMessageType")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.DescriptorProto, MessageTypeProxy>.plusAssign(values: kotlin.collections.Iterable<com.google.protobuf.DescriptorProtos.DescriptorProto>) {
      addAll(values)
    }
    /**
     * `repeated .google.protobuf.DescriptorProto message_type = 4 [json_name = "messageType"];`
     * @param index The index to set the value at.
     * @param value The messageType to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setMessageType")
    public operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.DescriptorProto, MessageTypeProxy>.set(index: kotlin.Int, value: com.google.protobuf.DescriptorProtos.DescriptorProto) {
      _builder.setMessageType(index, value)
    }
    /**
     * `repeated .google.protobuf.DescriptorProto message_type = 4 [json_name = "messageType"];`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearMessageType")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.DescriptorProto, MessageTypeProxy>.clear() {
      _builder.clearMessageType()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class EnumTypeProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .google.protobuf.EnumDescriptorProto enum_type = 5 [json_name = "enumType"];`
     */
     public val enumType: com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.EnumDescriptorProto, EnumTypeProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.enumTypeList
      )
    /**
     * `repeated .google.protobuf.EnumDescriptorProto enum_type = 5 [json_name = "enumType"];`
     * @param value The enumType to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addEnumType")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.EnumDescriptorProto, EnumTypeProxy>.add(value: com.google.protobuf.DescriptorProtos.EnumDescriptorProto) {
      _builder.addEnumType(value)
    }
    /**
     * `repeated .google.protobuf.EnumDescriptorProto enum_type = 5 [json_name = "enumType"];`
     * @param value The enumType to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignEnumType")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.EnumDescriptorProto, EnumTypeProxy>.plusAssign(value: com.google.protobuf.DescriptorProtos.EnumDescriptorProto) {
      add(value)
    }
    /**
     * `repeated .google.protobuf.EnumDescriptorProto enum_type = 5 [json_name = "enumType"];`
     * @param values The enumType to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllEnumType")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.EnumDescriptorProto, EnumTypeProxy>.addAll(values: kotlin.collections.Iterable<com.google.protobuf.DescriptorProtos.EnumDescriptorProto>) {
      _builder.addAllEnumType(values)
    }
    /**
     * `repeated .google.protobuf.EnumDescriptorProto enum_type = 5 [json_name = "enumType"];`
     * @param values The enumType to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllEnumType")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.EnumDescriptorProto, EnumTypeProxy>.plusAssign(values: kotlin.collections.Iterable<com.google.protobuf.DescriptorProtos.EnumDescriptorProto>) {
      addAll(values)
    }
    /**
     * `repeated .google.protobuf.EnumDescriptorProto enum_type = 5 [json_name = "enumType"];`
     * @param index The index to set the value at.
     * @param value The enumType to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setEnumType")
    public operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.EnumDescriptorProto, EnumTypeProxy>.set(index: kotlin.Int, value: com.google.protobuf.DescriptorProtos.EnumDescriptorProto) {
      _builder.setEnumType(index, value)
    }
    /**
     * `repeated .google.protobuf.EnumDescriptorProto enum_type = 5 [json_name = "enumType"];`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearEnumType")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.EnumDescriptorProto, EnumTypeProxy>.clear() {
      _builder.clearEnumType()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ServiceProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .google.protobuf.ServiceDescriptorProto service = 6 [json_name = "service"];`
     */
     public val service: com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.ServiceDescriptorProto, ServiceProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.serviceList
      )
    /**
     * `repeated .google.protobuf.ServiceDescriptorProto service = 6 [json_name = "service"];`
     * @param value The service to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addService")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.ServiceDescriptorProto, ServiceProxy>.add(value: com.google.protobuf.DescriptorProtos.ServiceDescriptorProto) {
      _builder.addService(value)
    }
    /**
     * `repeated .google.protobuf.ServiceDescriptorProto service = 6 [json_name = "service"];`
     * @param value The service to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignService")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.ServiceDescriptorProto, ServiceProxy>.plusAssign(value: com.google.protobuf.DescriptorProtos.ServiceDescriptorProto) {
      add(value)
    }
    /**
     * `repeated .google.protobuf.ServiceDescriptorProto service = 6 [json_name = "service"];`
     * @param values The service to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllService")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.ServiceDescriptorProto, ServiceProxy>.addAll(values: kotlin.collections.Iterable<com.google.protobuf.DescriptorProtos.ServiceDescriptorProto>) {
      _builder.addAllService(values)
    }
    /**
     * `repeated .google.protobuf.ServiceDescriptorProto service = 6 [json_name = "service"];`
     * @param values The service to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllService")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.ServiceDescriptorProto, ServiceProxy>.plusAssign(values: kotlin.collections.Iterable<com.google.protobuf.DescriptorProtos.ServiceDescriptorProto>) {
      addAll(values)
    }
    /**
     * `repeated .google.protobuf.ServiceDescriptorProto service = 6 [json_name = "service"];`
     * @param index The index to set the value at.
     * @param value The service to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setService")
    public operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.ServiceDescriptorProto, ServiceProxy>.set(index: kotlin.Int, value: com.google.protobuf.DescriptorProtos.ServiceDescriptorProto) {
      _builder.setService(index, value)
    }
    /**
     * `repeated .google.protobuf.ServiceDescriptorProto service = 6 [json_name = "service"];`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearService")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.ServiceDescriptorProto, ServiceProxy>.clear() {
      _builder.clearService()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ExtensionProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .google.protobuf.FieldDescriptorProto extension = 7 [json_name = "extension"];`
     */
     public val extension: com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.FieldDescriptorProto, ExtensionProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.extensionList
      )
    /**
     * `repeated .google.protobuf.FieldDescriptorProto extension = 7 [json_name = "extension"];`
     * @param value The extension to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addExtension")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.FieldDescriptorProto, ExtensionProxy>.add(value: com.google.protobuf.DescriptorProtos.FieldDescriptorProto) {
      _builder.addExtension(value)
    }
    /**
     * `repeated .google.protobuf.FieldDescriptorProto extension = 7 [json_name = "extension"];`
     * @param value The extension to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignExtension")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.FieldDescriptorProto, ExtensionProxy>.plusAssign(value: com.google.protobuf.DescriptorProtos.FieldDescriptorProto) {
      add(value)
    }
    /**
     * `repeated .google.protobuf.FieldDescriptorProto extension = 7 [json_name = "extension"];`
     * @param values The extension to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllExtension")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.FieldDescriptorProto, ExtensionProxy>.addAll(values: kotlin.collections.Iterable<com.google.protobuf.DescriptorProtos.FieldDescriptorProto>) {
      _builder.addAllExtension(values)
    }
    /**
     * `repeated .google.protobuf.FieldDescriptorProto extension = 7 [json_name = "extension"];`
     * @param values The extension to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllExtension")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.FieldDescriptorProto, ExtensionProxy>.plusAssign(values: kotlin.collections.Iterable<com.google.protobuf.DescriptorProtos.FieldDescriptorProto>) {
      addAll(values)
    }
    /**
     * `repeated .google.protobuf.FieldDescriptorProto extension = 7 [json_name = "extension"];`
     * @param index The index to set the value at.
     * @param value The extension to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setExtension")
    public operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.FieldDescriptorProto, ExtensionProxy>.set(index: kotlin.Int, value: com.google.protobuf.DescriptorProtos.FieldDescriptorProto) {
      _builder.setExtension(index, value)
    }
    /**
     * `repeated .google.protobuf.FieldDescriptorProto extension = 7 [json_name = "extension"];`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearExtension")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.FieldDescriptorProto, ExtensionProxy>.clear() {
      _builder.clearExtension()
    }

    /**
     * `optional .google.protobuf.FileOptions options = 8 [json_name = "options"];`
     */
    public var options: com.google.protobuf.DescriptorProtos.FileOptions
      @JvmName("getOptions")
      get() = _builder.options
      @JvmName("setOptions")
      set(value) {
        _builder.options = value
      }
    /**
     * `optional .google.protobuf.FileOptions options = 8 [json_name = "options"];`
     */
    public fun clearOptions() {
      _builder.clearOptions()
    }
    /**
     * `optional .google.protobuf.FileOptions options = 8 [json_name = "options"];`
     * @return Whether the options field is set.
     */
    public fun hasOptions(): kotlin.Boolean {
      return _builder.hasOptions()
    }
    public val FileDescriptorProtoKt.Dsl.optionsOrNull: com.google.protobuf.DescriptorProtos.FileOptions?
      get() = _builder.optionsOrNull

    /**
     * `optional .google.protobuf.SourceCodeInfo source_code_info = 9 [json_name = "sourceCodeInfo"];`
     */
    public var sourceCodeInfo: com.google.protobuf.DescriptorProtos.SourceCodeInfo
      @JvmName("getSourceCodeInfo")
      get() = _builder.sourceCodeInfo
      @JvmName("setSourceCodeInfo")
      set(value) {
        _builder.sourceCodeInfo = value
      }
    /**
     * `optional .google.protobuf.SourceCodeInfo source_code_info = 9 [json_name = "sourceCodeInfo"];`
     */
    public fun clearSourceCodeInfo() {
      _builder.clearSourceCodeInfo()
    }
    /**
     * `optional .google.protobuf.SourceCodeInfo source_code_info = 9 [json_name = "sourceCodeInfo"];`
     * @return Whether the sourceCodeInfo field is set.
     */
    public fun hasSourceCodeInfo(): kotlin.Boolean {
      return _builder.hasSourceCodeInfo()
    }
    public val FileDescriptorProtoKt.Dsl.sourceCodeInfoOrNull: com.google.protobuf.DescriptorProtos.SourceCodeInfo?
      get() = _builder.sourceCodeInfoOrNull

    /**
     * `optional string syntax = 12 [json_name = "syntax"];`
     */
    public var syntax: kotlin.String
      @JvmName("getSyntax")
      get() = _builder.syntax
      @JvmName("setSyntax")
      set(value) {
        _builder.syntax = value
      }
    /**
     * `optional string syntax = 12 [json_name = "syntax"];`
     */
    public fun clearSyntax() {
      _builder.clearSyntax()
    }
    /**
     * `optional string syntax = 12 [json_name = "syntax"];`
     * @return Whether the syntax field is set.
     */
    public fun hasSyntax(): kotlin.Boolean {
      return _builder.hasSyntax()
    }

    /**
     * `optional .google.protobuf.Edition edition = 14 [json_name = "edition"];`
     */
    public var edition: com.google.protobuf.DescriptorProtos.Edition
      @JvmName("getEdition")
      get() = _builder.edition
      @JvmName("setEdition")
      set(value) {
        _builder.edition = value
      }
    /**
     * `optional .google.protobuf.Edition edition = 14 [json_name = "edition"];`
     */
    public fun clearEdition() {
      _builder.clearEdition()
    }
    /**
     * `optional .google.protobuf.Edition edition = 14 [json_name = "edition"];`
     * @return Whether the edition field is set.
     */
    public fun hasEdition(): kotlin.Boolean {
      return _builder.hasEdition()
    }
  }
}
public inline fun com.google.protobuf.DescriptorProtos.FileDescriptorProto.copy(block: `com.google.protobuf`.FileDescriptorProtoKt.Dsl.() -> kotlin.Unit): com.google.protobuf.DescriptorProtos.FileDescriptorProto =
  `com.google.protobuf`.FileDescriptorProtoKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.google.protobuf.DescriptorProtos.FileDescriptorProtoOrBuilder.optionsOrNull: com.google.protobuf.DescriptorProtos.FileOptions?
  get() = if (hasOptions()) getOptions() else null

public val com.google.protobuf.DescriptorProtos.FileDescriptorProtoOrBuilder.sourceCodeInfoOrNull: com.google.protobuf.DescriptorProtos.SourceCodeInfo?
  get() = if (hasSourceCodeInfo()) getSourceCodeInfo() else null

