// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/protobuf/descriptor.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.google.protobuf;

@kotlin.jvm.JvmName("-initializegeneratedCodeInfo")
public inline fun generatedCodeInfo(block: com.google.protobuf.GeneratedCodeInfoKt.Dsl.() -> kotlin.Unit): com.google.protobuf.DescriptorProtos.GeneratedCodeInfo =
  com.google.protobuf.GeneratedCodeInfoKt.Dsl._create(com.google.protobuf.DescriptorProtos.GeneratedCodeInfo.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `google.protobuf.GeneratedCodeInfo`
 */
public object GeneratedCodeInfoKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.google.protobuf.DescriptorProtos.GeneratedCodeInfo.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.google.protobuf.DescriptorProtos.GeneratedCodeInfo.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.google.protobuf.DescriptorProtos.GeneratedCodeInfo = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class AnnotationProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .google.protobuf.GeneratedCodeInfo.Annotation annotation = 1 [json_name = "annotation"];`
     */
     public val annotation: com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.GeneratedCodeInfo.Annotation, AnnotationProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.annotationList
      )
    /**
     * `repeated .google.protobuf.GeneratedCodeInfo.Annotation annotation = 1 [json_name = "annotation"];`
     * @param value The annotation to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAnnotation")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.GeneratedCodeInfo.Annotation, AnnotationProxy>.add(value: com.google.protobuf.DescriptorProtos.GeneratedCodeInfo.Annotation) {
      _builder.addAnnotation(value)
    }
    /**
     * `repeated .google.protobuf.GeneratedCodeInfo.Annotation annotation = 1 [json_name = "annotation"];`
     * @param value The annotation to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAnnotation")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.GeneratedCodeInfo.Annotation, AnnotationProxy>.plusAssign(value: com.google.protobuf.DescriptorProtos.GeneratedCodeInfo.Annotation) {
      add(value)
    }
    /**
     * `repeated .google.protobuf.GeneratedCodeInfo.Annotation annotation = 1 [json_name = "annotation"];`
     * @param values The annotation to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllAnnotation")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.GeneratedCodeInfo.Annotation, AnnotationProxy>.addAll(values: kotlin.collections.Iterable<com.google.protobuf.DescriptorProtos.GeneratedCodeInfo.Annotation>) {
      _builder.addAllAnnotation(values)
    }
    /**
     * `repeated .google.protobuf.GeneratedCodeInfo.Annotation annotation = 1 [json_name = "annotation"];`
     * @param values The annotation to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllAnnotation")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.GeneratedCodeInfo.Annotation, AnnotationProxy>.plusAssign(values: kotlin.collections.Iterable<com.google.protobuf.DescriptorProtos.GeneratedCodeInfo.Annotation>) {
      addAll(values)
    }
    /**
     * `repeated .google.protobuf.GeneratedCodeInfo.Annotation annotation = 1 [json_name = "annotation"];`
     * @param index The index to set the value at.
     * @param value The annotation to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setAnnotation")
    public operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.GeneratedCodeInfo.Annotation, AnnotationProxy>.set(index: kotlin.Int, value: com.google.protobuf.DescriptorProtos.GeneratedCodeInfo.Annotation) {
      _builder.setAnnotation(index, value)
    }
    /**
     * `repeated .google.protobuf.GeneratedCodeInfo.Annotation annotation = 1 [json_name = "annotation"];`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearAnnotation")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.GeneratedCodeInfo.Annotation, AnnotationProxy>.clear() {
      _builder.clearAnnotation()
    }
  }
  @kotlin.jvm.JvmName("-initializeannotation")
  public inline fun annotation(block: com.google.protobuf.GeneratedCodeInfoKt.AnnotationKt.Dsl.() -> kotlin.Unit): com.google.protobuf.DescriptorProtos.GeneratedCodeInfo.Annotation =
    com.google.protobuf.GeneratedCodeInfoKt.AnnotationKt.Dsl._create(com.google.protobuf.DescriptorProtos.GeneratedCodeInfo.Annotation.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `google.protobuf.GeneratedCodeInfo.Annotation`
   */
  public object AnnotationKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: com.google.protobuf.DescriptorProtos.GeneratedCodeInfo.Annotation.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _create(builder: com.google.protobuf.DescriptorProtos.GeneratedCodeInfo.Annotation.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _build(): com.google.protobuf.DescriptorProtos.GeneratedCodeInfo.Annotation = _builder.build()

      /**
       * An uninstantiable, behaviorless type to represent the field in
       * generics.
       */
      @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      public class PathProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
      /**
       * <code>repeated int32 path = 1 [json_name = "path", packed = true];</code>
       */
       public val path: com.google.protobuf.kotlin.DslList<kotlin.Int, PathProxy>
        @kotlin.jvm.JvmSynthetic
        get() = com.google.protobuf.kotlin.DslList(
          _builder.pathList
        )
      /**
       * `repeated int32 path = 1 [json_name = "path", packed = true];`
       * @param value The path to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("addPath")
      public fun com.google.protobuf.kotlin.DslList<kotlin.Int, PathProxy>.add(value: kotlin.Int) {
        _builder.addPath(value)
      }/**
       * `repeated int32 path = 1 [json_name = "path", packed = true];`
       * @param value The path to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("plusAssignPath")
      @Suppress("NOTHING_TO_INLINE")
      public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Int, PathProxy>.plusAssign(value: kotlin.Int) {
        add(value)
      }/**
       * `repeated int32 path = 1 [json_name = "path", packed = true];`
       * @param values The path to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("addAllPath")
      public fun com.google.protobuf.kotlin.DslList<kotlin.Int, PathProxy>.addAll(values: kotlin.collections.Iterable<kotlin.Int>) {
        _builder.addAllPath(values)
      }/**
       * `repeated int32 path = 1 [json_name = "path", packed = true];`
       * @param values The path to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("plusAssignAllPath")
      @Suppress("NOTHING_TO_INLINE")
      public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Int, PathProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.Int>) {
        addAll(values)
      }/**
       * `repeated int32 path = 1 [json_name = "path", packed = true];`
       * @param index The index to set the value at.
       * @param value The path to set.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("setPath")
      public operator fun com.google.protobuf.kotlin.DslList<kotlin.Int, PathProxy>.set(index: kotlin.Int, value: kotlin.Int) {
        _builder.setPath(index, value)
      }/**
       * `repeated int32 path = 1 [json_name = "path", packed = true];`
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("clearPath")
      public fun com.google.protobuf.kotlin.DslList<kotlin.Int, PathProxy>.clear() {
        _builder.clearPath()
      }
      /**
       * `optional string source_file = 2 [json_name = "sourceFile"];`
       */
      public var sourceFile: kotlin.String
        @JvmName("getSourceFile")
        get() = _builder.sourceFile
        @JvmName("setSourceFile")
        set(value) {
          _builder.sourceFile = value
        }
      /**
       * `optional string source_file = 2 [json_name = "sourceFile"];`
       */
      public fun clearSourceFile() {
        _builder.clearSourceFile()
      }
      /**
       * `optional string source_file = 2 [json_name = "sourceFile"];`
       * @return Whether the sourceFile field is set.
       */
      public fun hasSourceFile(): kotlin.Boolean {
        return _builder.hasSourceFile()
      }

      /**
       * <code>optional int32 begin = 3 [json_name = "begin"];</code>
       */
      public var begin: kotlin.Int
        @JvmName("getBegin")
        get() = _builder.begin
        @JvmName("setBegin")
        set(value) {
          _builder.begin = value
        }
      /**
       * `optional int32 begin = 3 [json_name = "begin"];`
       */
      public fun clearBegin() {
        _builder.clearBegin()
      }
      /**
       * `optional int32 begin = 3 [json_name = "begin"];`
       * @return Whether the begin field is set.
       */
      public fun hasBegin(): kotlin.Boolean {
        return _builder.hasBegin()
      }

      /**
       * <code>optional int32 end = 4 [json_name = "end"];</code>
       */
      public var end: kotlin.Int
        @JvmName("getEnd")
        get() = _builder.end
        @JvmName("setEnd")
        set(value) {
          _builder.end = value
        }
      /**
       * `optional int32 end = 4 [json_name = "end"];`
       */
      public fun clearEnd() {
        _builder.clearEnd()
      }
      /**
       * `optional int32 end = 4 [json_name = "end"];`
       * @return Whether the end field is set.
       */
      public fun hasEnd(): kotlin.Boolean {
        return _builder.hasEnd()
      }

      /**
       * `optional .google.protobuf.GeneratedCodeInfo.Annotation.Semantic semantic = 5 [json_name = "semantic"];`
       */
      public var semantic: com.google.protobuf.DescriptorProtos.GeneratedCodeInfo.Annotation.Semantic
        @JvmName("getSemantic")
        get() = _builder.semantic
        @JvmName("setSemantic")
        set(value) {
          _builder.semantic = value
        }
      /**
       * `optional .google.protobuf.GeneratedCodeInfo.Annotation.Semantic semantic = 5 [json_name = "semantic"];`
       */
      public fun clearSemantic() {
        _builder.clearSemantic()
      }
      /**
       * `optional .google.protobuf.GeneratedCodeInfo.Annotation.Semantic semantic = 5 [json_name = "semantic"];`
       * @return Whether the semantic field is set.
       */
      public fun hasSemantic(): kotlin.Boolean {
        return _builder.hasSemantic()
      }
    }
  }
}
public inline fun com.google.protobuf.DescriptorProtos.GeneratedCodeInfo.copy(block: `com.google.protobuf`.GeneratedCodeInfoKt.Dsl.() -> kotlin.Unit): com.google.protobuf.DescriptorProtos.GeneratedCodeInfo =
  `com.google.protobuf`.GeneratedCodeInfoKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public inline fun com.google.protobuf.DescriptorProtos.GeneratedCodeInfo.Annotation.copy(block: `com.google.protobuf`.GeneratedCodeInfoKt.AnnotationKt.Dsl.() -> kotlin.Unit): com.google.protobuf.DescriptorProtos.GeneratedCodeInfo.Annotation =
  `com.google.protobuf`.GeneratedCodeInfoKt.AnnotationKt.Dsl._create(this.toBuilder()).apply { block() }._build()

