// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/protobuf/wrappers.proto
// Protobuf Java Version: 4.28.3

package com.google.protobuf;

public interface Int64ValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.protobuf.Int64Value)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>int64 value = 1 [json_name = "value"];</code>
   * @return The value.
   */
  long getValue();
}
