// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/protobuf/java_features.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.google.protobuf;

@kotlin.jvm.JvmName("-initializejavaFeatures")
public inline fun javaFeatures(block: com.google.protobuf.JavaFeaturesKt.Dsl.() -> kotlin.Unit): com.google.protobuf.JavaFeaturesProto.JavaFeatures =
  com.google.protobuf.JavaFeaturesKt.Dsl._create(com.google.protobuf.JavaFeaturesProto.JavaFeatures.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `pb.JavaFeatures`
 */
public object JavaFeaturesKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.google.protobuf.JavaFeaturesProto.JavaFeatures.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.google.protobuf.JavaFeaturesProto.JavaFeatures.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.google.protobuf.JavaFeaturesProto.JavaFeatures = _builder.build()

    /**
     * <code>optional bool legacy_closed_enum = 1 [json_name = "legacyClosedEnum", retention = RETENTION_RUNTIME, targets = TARGET_TYPE_FIELD, targets = TARGET_TYPE_FILE, edition_defaults = { ... }</code>
     */
    public var legacyClosedEnum: kotlin.Boolean
      @JvmName("getLegacyClosedEnum")
      get() = _builder.legacyClosedEnum
      @JvmName("setLegacyClosedEnum")
      set(value) {
        _builder.legacyClosedEnum = value
      }
    /**
     * `optional bool legacy_closed_enum = 1 [json_name = "legacyClosedEnum", retention = RETENTION_RUNTIME, targets = TARGET_TYPE_FIELD, targets = TARGET_TYPE_FILE, edition_defaults = { ... }`
     */
    public fun clearLegacyClosedEnum() {
      _builder.clearLegacyClosedEnum()
    }
    /**
     * `optional bool legacy_closed_enum = 1 [json_name = "legacyClosedEnum", retention = RETENTION_RUNTIME, targets = TARGET_TYPE_FIELD, targets = TARGET_TYPE_FILE, edition_defaults = { ... }`
     * @return Whether the legacyClosedEnum field is set.
     */
    public fun hasLegacyClosedEnum(): kotlin.Boolean {
      return _builder.hasLegacyClosedEnum()
    }

    /**
     * `optional .pb.JavaFeatures.Utf8Validation utf8_validation = 2 [json_name = "utf8Validation", retention = RETENTION_RUNTIME, targets = TARGET_TYPE_FIELD, targets = TARGET_TYPE_FILE, edition_defaults = { ... }`
     */
    public var utf8Validation: com.google.protobuf.JavaFeaturesProto.JavaFeatures.Utf8Validation
      @JvmName("getUtf8Validation")
      get() = _builder.utf8Validation
      @JvmName("setUtf8Validation")
      set(value) {
        _builder.utf8Validation = value
      }
    /**
     * `optional .pb.JavaFeatures.Utf8Validation utf8_validation = 2 [json_name = "utf8Validation", retention = RETENTION_RUNTIME, targets = TARGET_TYPE_FIELD, targets = TARGET_TYPE_FILE, edition_defaults = { ... }`
     */
    public fun clearUtf8Validation() {
      _builder.clearUtf8Validation()
    }
    /**
     * `optional .pb.JavaFeatures.Utf8Validation utf8_validation = 2 [json_name = "utf8Validation", retention = RETENTION_RUNTIME, targets = TARGET_TYPE_FIELD, targets = TARGET_TYPE_FILE, edition_defaults = { ... }`
     * @return Whether the utf8Validation field is set.
     */
    public fun hasUtf8Validation(): kotlin.Boolean {
      return _builder.hasUtf8Validation()
    }
  }
}
public inline fun com.google.protobuf.JavaFeaturesProto.JavaFeatures.copy(block: `com.google.protobuf`.JavaFeaturesKt.Dsl.() -> kotlin.Unit): com.google.protobuf.JavaFeaturesProto.JavaFeatures =
  `com.google.protobuf`.JavaFeaturesKt.Dsl._create(this.toBuilder()).apply { block() }._build()

