// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/protobuf/struct.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.google.protobuf;

@kotlin.jvm.JvmName("-initializelistValue")
public inline fun listValue(block: com.google.protobuf.ListValueKt.Dsl.() -> kotlin.Unit): com.google.protobuf.ListValue =
  com.google.protobuf.ListValueKt.Dsl._create(com.google.protobuf.ListValue.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `google.protobuf.ListValue`
 */
public object ListValueKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.google.protobuf.ListValue.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.google.protobuf.ListValue.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.google.protobuf.ListValue = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ValuesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .google.protobuf.Value values = 1 [json_name = "values"];`
     */
     public val values: com.google.protobuf.kotlin.DslList<com.google.protobuf.Value, ValuesProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.valuesList
      )
    /**
     * `repeated .google.protobuf.Value values = 1 [json_name = "values"];`
     * @param value The values to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addValues")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Value, ValuesProxy>.add(value: com.google.protobuf.Value) {
      _builder.addValues(value)
    }
    /**
     * `repeated .google.protobuf.Value values = 1 [json_name = "values"];`
     * @param value The values to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignValues")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Value, ValuesProxy>.plusAssign(value: com.google.protobuf.Value) {
      add(value)
    }
    /**
     * `repeated .google.protobuf.Value values = 1 [json_name = "values"];`
     * @param values The values to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllValues")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Value, ValuesProxy>.addAll(values: kotlin.collections.Iterable<com.google.protobuf.Value>) {
      _builder.addAllValues(values)
    }
    /**
     * `repeated .google.protobuf.Value values = 1 [json_name = "values"];`
     * @param values The values to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllValues")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Value, ValuesProxy>.plusAssign(values: kotlin.collections.Iterable<com.google.protobuf.Value>) {
      addAll(values)
    }
    /**
     * `repeated .google.protobuf.Value values = 1 [json_name = "values"];`
     * @param index The index to set the value at.
     * @param value The values to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setValues")
    public operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Value, ValuesProxy>.set(index: kotlin.Int, value: com.google.protobuf.Value) {
      _builder.setValues(index, value)
    }
    /**
     * `repeated .google.protobuf.Value values = 1 [json_name = "values"];`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearValues")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Value, ValuesProxy>.clear() {
      _builder.clearValues()
    }
  }
}
public inline fun com.google.protobuf.ListValue.copy(block: `com.google.protobuf`.ListValueKt.Dsl.() -> kotlin.Unit): com.google.protobuf.ListValue =
  `com.google.protobuf`.ListValueKt.Dsl._create(this.toBuilder()).apply { block() }._build()

