// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/protobuf/descriptor.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.google.protobuf;

@kotlin.jvm.JvmName("-initializemessageOptions")
public inline fun messageOptions(block: com.google.protobuf.MessageOptionsKt.Dsl.() -> kotlin.Unit): com.google.protobuf.DescriptorProtos.MessageOptions =
  com.google.protobuf.MessageOptionsKt.Dsl._create(com.google.protobuf.DescriptorProtos.MessageOptions.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `google.protobuf.MessageOptions`
 */
public object MessageOptionsKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.google.protobuf.DescriptorProtos.MessageOptions.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.google.protobuf.DescriptorProtos.MessageOptions.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.google.protobuf.DescriptorProtos.MessageOptions = _builder.build()

    /**
     * <code>optional bool message_set_wire_format = 1 [default = false, json_name = "messageSetWireFormat"];</code>
     */
    public var messageSetWireFormat: kotlin.Boolean
      @JvmName("getMessageSetWireFormat")
      get() = _builder.messageSetWireFormat
      @JvmName("setMessageSetWireFormat")
      set(value) {
        _builder.messageSetWireFormat = value
      }
    /**
     * `optional bool message_set_wire_format = 1 [default = false, json_name = "messageSetWireFormat"];`
     */
    public fun clearMessageSetWireFormat() {
      _builder.clearMessageSetWireFormat()
    }
    /**
     * `optional bool message_set_wire_format = 1 [default = false, json_name = "messageSetWireFormat"];`
     * @return Whether the messageSetWireFormat field is set.
     */
    public fun hasMessageSetWireFormat(): kotlin.Boolean {
      return _builder.hasMessageSetWireFormat()
    }

    /**
     * <code>optional bool no_standard_descriptor_accessor = 2 [default = false, json_name = "noStandardDescriptorAccessor"];</code>
     */
    public var noStandardDescriptorAccessor: kotlin.Boolean
      @JvmName("getNoStandardDescriptorAccessor")
      get() = _builder.noStandardDescriptorAccessor
      @JvmName("setNoStandardDescriptorAccessor")
      set(value) {
        _builder.noStandardDescriptorAccessor = value
      }
    /**
     * `optional bool no_standard_descriptor_accessor = 2 [default = false, json_name = "noStandardDescriptorAccessor"];`
     */
    public fun clearNoStandardDescriptorAccessor() {
      _builder.clearNoStandardDescriptorAccessor()
    }
    /**
     * `optional bool no_standard_descriptor_accessor = 2 [default = false, json_name = "noStandardDescriptorAccessor"];`
     * @return Whether the noStandardDescriptorAccessor field is set.
     */
    public fun hasNoStandardDescriptorAccessor(): kotlin.Boolean {
      return _builder.hasNoStandardDescriptorAccessor()
    }

    /**
     * <code>optional bool deprecated = 3 [default = false, json_name = "deprecated"];</code>
     */
    public var deprecated: kotlin.Boolean
      @JvmName("getDeprecated")
      get() = _builder.deprecated
      @JvmName("setDeprecated")
      set(value) {
        _builder.deprecated = value
      }
    /**
     * `optional bool deprecated = 3 [default = false, json_name = "deprecated"];`
     */
    public fun clearDeprecated() {
      _builder.clearDeprecated()
    }
    /**
     * `optional bool deprecated = 3 [default = false, json_name = "deprecated"];`
     * @return Whether the deprecated field is set.
     */
    public fun hasDeprecated(): kotlin.Boolean {
      return _builder.hasDeprecated()
    }

    /**
     * <code>optional bool map_entry = 7 [json_name = "mapEntry"];</code>
     */
    public var mapEntry: kotlin.Boolean
      @JvmName("getMapEntry")
      get() = _builder.mapEntry
      @JvmName("setMapEntry")
      set(value) {
        _builder.mapEntry = value
      }
    /**
     * `optional bool map_entry = 7 [json_name = "mapEntry"];`
     */
    public fun clearMapEntry() {
      _builder.clearMapEntry()
    }
    /**
     * `optional bool map_entry = 7 [json_name = "mapEntry"];`
     * @return Whether the mapEntry field is set.
     */
    public fun hasMapEntry(): kotlin.Boolean {
      return _builder.hasMapEntry()
    }

    /**
     * <code>optional bool deprecated_legacy_json_field_conflicts = 11 [json_name = "deprecatedLegacyJsonFieldConflicts", deprecated = true];</code>
     */
    @kotlin.Deprecated(message = "Field deprecatedLegacyJsonFieldConflicts is deprecated") public var deprecatedLegacyJsonFieldConflicts: kotlin.Boolean
      @JvmName("getDeprecatedLegacyJsonFieldConflicts")
      get() = _builder.deprecatedLegacyJsonFieldConflicts
      @JvmName("setDeprecatedLegacyJsonFieldConflicts")
      set(value) {
        _builder.deprecatedLegacyJsonFieldConflicts = value
      }
    /**
     * `optional bool deprecated_legacy_json_field_conflicts = 11 [json_name = "deprecatedLegacyJsonFieldConflicts", deprecated = true];`
     */
    public fun clearDeprecatedLegacyJsonFieldConflicts() {
      _builder.clearDeprecatedLegacyJsonFieldConflicts()
    }
    /**
     * `optional bool deprecated_legacy_json_field_conflicts = 11 [json_name = "deprecatedLegacyJsonFieldConflicts", deprecated = true];`
     * @return Whether the deprecatedLegacyJsonFieldConflicts field is set.
     */
    public fun hasDeprecatedLegacyJsonFieldConflicts(): kotlin.Boolean {
      return _builder.hasDeprecatedLegacyJsonFieldConflicts()
    }

    /**
     * `optional .google.protobuf.FeatureSet features = 12 [json_name = "features"];`
     */
    public var features: com.google.protobuf.DescriptorProtos.FeatureSet
      @JvmName("getFeatures")
      get() = _builder.features
      @JvmName("setFeatures")
      set(value) {
        _builder.features = value
      }
    /**
     * `optional .google.protobuf.FeatureSet features = 12 [json_name = "features"];`
     */
    public fun clearFeatures() {
      _builder.clearFeatures()
    }
    /**
     * `optional .google.protobuf.FeatureSet features = 12 [json_name = "features"];`
     * @return Whether the features field is set.
     */
    public fun hasFeatures(): kotlin.Boolean {
      return _builder.hasFeatures()
    }
    public val MessageOptionsKt.Dsl.featuresOrNull: com.google.protobuf.DescriptorProtos.FeatureSet?
      get() = _builder.featuresOrNull

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class UninterpretedOptionProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999 [json_name = "uninterpretedOption"];`
     */
     public val uninterpretedOption: com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.UninterpretedOption, UninterpretedOptionProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.uninterpretedOptionList
      )
    /**
     * `repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999 [json_name = "uninterpretedOption"];`
     * @param value The uninterpretedOption to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addUninterpretedOption")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.UninterpretedOption, UninterpretedOptionProxy>.add(value: com.google.protobuf.DescriptorProtos.UninterpretedOption) {
      _builder.addUninterpretedOption(value)
    }
    /**
     * `repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999 [json_name = "uninterpretedOption"];`
     * @param value The uninterpretedOption to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignUninterpretedOption")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.UninterpretedOption, UninterpretedOptionProxy>.plusAssign(value: com.google.protobuf.DescriptorProtos.UninterpretedOption) {
      add(value)
    }
    /**
     * `repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999 [json_name = "uninterpretedOption"];`
     * @param values The uninterpretedOption to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllUninterpretedOption")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.UninterpretedOption, UninterpretedOptionProxy>.addAll(values: kotlin.collections.Iterable<com.google.protobuf.DescriptorProtos.UninterpretedOption>) {
      _builder.addAllUninterpretedOption(values)
    }
    /**
     * `repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999 [json_name = "uninterpretedOption"];`
     * @param values The uninterpretedOption to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllUninterpretedOption")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.UninterpretedOption, UninterpretedOptionProxy>.plusAssign(values: kotlin.collections.Iterable<com.google.protobuf.DescriptorProtos.UninterpretedOption>) {
      addAll(values)
    }
    /**
     * `repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999 [json_name = "uninterpretedOption"];`
     * @param index The index to set the value at.
     * @param value The uninterpretedOption to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setUninterpretedOption")
    public operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.UninterpretedOption, UninterpretedOptionProxy>.set(index: kotlin.Int, value: com.google.protobuf.DescriptorProtos.UninterpretedOption) {
      _builder.setUninterpretedOption(index, value)
    }
    /**
     * `repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999 [json_name = "uninterpretedOption"];`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearUninterpretedOption")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.UninterpretedOption, UninterpretedOptionProxy>.clear() {
      _builder.clearUninterpretedOption()
    }
    @Suppress("UNCHECKED_CAST")
    @kotlin.jvm.JvmSynthetic
    public operator fun <T : kotlin.Any> get(extension: com.google.protobuf.ExtensionLite<com.google.protobuf.DescriptorProtos.MessageOptions, T>): T {
      return if (extension.isRepeated) {
        get(extension as com.google.protobuf.ExtensionLite<com.google.protobuf.DescriptorProtos.MessageOptions, kotlin.collections.List<*>>) as T
      } else {
        _builder.getExtension(extension)
      }
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @kotlin.jvm.JvmName("-getRepeatedExtension")
    public operator fun <E : kotlin.Any> get(
      extension: com.google.protobuf.ExtensionLite<com.google.protobuf.DescriptorProtos.MessageOptions, kotlin.collections.List<E>>
    ): com.google.protobuf.kotlin.ExtensionList<E, com.google.protobuf.DescriptorProtos.MessageOptions> {
      return com.google.protobuf.kotlin.ExtensionList(extension, _builder.getExtension(extension))
    }

    @kotlin.jvm.JvmSynthetic
    public operator fun contains(extension: com.google.protobuf.ExtensionLite<com.google.protobuf.DescriptorProtos.MessageOptions, *>): Boolean {
      return _builder.hasExtension(extension)
    }

    @kotlin.jvm.JvmSynthetic
    public fun clear(extension: com.google.protobuf.ExtensionLite<com.google.protobuf.DescriptorProtos.MessageOptions, *>) {
      _builder.clearExtension(extension)
    }

    @kotlin.jvm.JvmSynthetic
    public fun <T : kotlin.Any> setExtension(extension: com.google.protobuf.ExtensionLite<com.google.protobuf.DescriptorProtos.MessageOptions, T>, value: T) {
      _builder.setExtension(extension, value)
    }

    @kotlin.jvm.JvmSynthetic
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun <T : Comparable<T>> set(
      extension: com.google.protobuf.ExtensionLite<com.google.protobuf.DescriptorProtos.MessageOptions, T>,
      value: T
    ) {
      setExtension(extension, value)
    }

    @kotlin.jvm.JvmSynthetic
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun set(
      extension: com.google.protobuf.ExtensionLite<com.google.protobuf.DescriptorProtos.MessageOptions, com.google.protobuf.ByteString>,
      value: com.google.protobuf.ByteString
    ) {
      setExtension(extension, value)
    }

    @kotlin.jvm.JvmSynthetic
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun <T : com.google.protobuf.MessageLite> set(
      extension: com.google.protobuf.ExtensionLite<com.google.protobuf.DescriptorProtos.MessageOptions, T>,
      value: T
    ) {
      setExtension(extension, value)
    }

    @kotlin.jvm.JvmSynthetic
    public fun<E : kotlin.Any> com.google.protobuf.kotlin.ExtensionList<E, com.google.protobuf.DescriptorProtos.MessageOptions>.add(value: E) {
      _builder.addExtension(this.extension, value)
    }

    @kotlin.jvm.JvmSynthetic
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun <E : kotlin.Any> com.google.protobuf.kotlin.ExtensionList<E, com.google.protobuf.DescriptorProtos.MessageOptions>.plusAssign(value: E) {
      add(value)
    }

    @kotlin.jvm.JvmSynthetic
    public fun<E : kotlin.Any> com.google.protobuf.kotlin.ExtensionList<E, com.google.protobuf.DescriptorProtos.MessageOptions>.addAll(values: Iterable<E>) {
      for (value in values) {
        add(value)
      }
    }

    @kotlin.jvm.JvmSynthetic
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun <E : kotlin.Any> com.google.protobuf.kotlin.ExtensionList<E, com.google.protobuf.DescriptorProtos.MessageOptions>.plusAssign(values: Iterable<E>) {
      addAll(values)
    }

    @kotlin.jvm.JvmSynthetic
    public operator fun <E : kotlin.Any> com.google.protobuf.kotlin.ExtensionList<E, com.google.protobuf.DescriptorProtos.MessageOptions>.set(index: Int, value: E) {
      _builder.setExtension(this.extension, index, value)
    }

    @kotlin.jvm.JvmSynthetic
    @Suppress("NOTHING_TO_INLINE")
    public inline fun com.google.protobuf.kotlin.ExtensionList<*, com.google.protobuf.DescriptorProtos.MessageOptions>.clear() {
      clear(extension)
    }

  }
}
public inline fun com.google.protobuf.DescriptorProtos.MessageOptions.copy(block: `com.google.protobuf`.MessageOptionsKt.Dsl.() -> kotlin.Unit): com.google.protobuf.DescriptorProtos.MessageOptions =
  `com.google.protobuf`.MessageOptionsKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.google.protobuf.DescriptorProtos.MessageOptionsOrBuilder.featuresOrNull: com.google.protobuf.DescriptorProtos.FeatureSet?
  get() = if (hasFeatures()) getFeatures() else null

