// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/protobuf/descriptor.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.google.protobuf;

@kotlin.jvm.JvmName("-initializemethodDescriptorProto")
public inline fun methodDescriptorProto(block: com.google.protobuf.MethodDescriptorProtoKt.Dsl.() -> kotlin.Unit): com.google.protobuf.DescriptorProtos.MethodDescriptorProto =
  com.google.protobuf.MethodDescriptorProtoKt.Dsl._create(com.google.protobuf.DescriptorProtos.MethodDescriptorProto.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `google.protobuf.MethodDescriptorProto`
 */
public object MethodDescriptorProtoKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.google.protobuf.DescriptorProtos.MethodDescriptorProto.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.google.protobuf.DescriptorProtos.MethodDescriptorProto.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.google.protobuf.DescriptorProtos.MethodDescriptorProto = _builder.build()

    /**
     * `optional string name = 1 [json_name = "name"];`
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.name
      @JvmName("setName")
      set(value) {
        _builder.name = value
      }
    /**
     * `optional string name = 1 [json_name = "name"];`
     */
    public fun clearName() {
      _builder.clearName()
    }
    /**
     * `optional string name = 1 [json_name = "name"];`
     * @return Whether the name field is set.
     */
    public fun hasName(): kotlin.Boolean {
      return _builder.hasName()
    }

    /**
     * `optional string input_type = 2 [json_name = "inputType"];`
     */
    public var inputType: kotlin.String
      @JvmName("getInputType")
      get() = _builder.inputType
      @JvmName("setInputType")
      set(value) {
        _builder.inputType = value
      }
    /**
     * `optional string input_type = 2 [json_name = "inputType"];`
     */
    public fun clearInputType() {
      _builder.clearInputType()
    }
    /**
     * `optional string input_type = 2 [json_name = "inputType"];`
     * @return Whether the inputType field is set.
     */
    public fun hasInputType(): kotlin.Boolean {
      return _builder.hasInputType()
    }

    /**
     * `optional string output_type = 3 [json_name = "outputType"];`
     */
    public var outputType: kotlin.String
      @JvmName("getOutputType")
      get() = _builder.outputType
      @JvmName("setOutputType")
      set(value) {
        _builder.outputType = value
      }
    /**
     * `optional string output_type = 3 [json_name = "outputType"];`
     */
    public fun clearOutputType() {
      _builder.clearOutputType()
    }
    /**
     * `optional string output_type = 3 [json_name = "outputType"];`
     * @return Whether the outputType field is set.
     */
    public fun hasOutputType(): kotlin.Boolean {
      return _builder.hasOutputType()
    }

    /**
     * `optional .google.protobuf.MethodOptions options = 4 [json_name = "options"];`
     */
    public var options: com.google.protobuf.DescriptorProtos.MethodOptions
      @JvmName("getOptions")
      get() = _builder.options
      @JvmName("setOptions")
      set(value) {
        _builder.options = value
      }
    /**
     * `optional .google.protobuf.MethodOptions options = 4 [json_name = "options"];`
     */
    public fun clearOptions() {
      _builder.clearOptions()
    }
    /**
     * `optional .google.protobuf.MethodOptions options = 4 [json_name = "options"];`
     * @return Whether the options field is set.
     */
    public fun hasOptions(): kotlin.Boolean {
      return _builder.hasOptions()
    }
    public val MethodDescriptorProtoKt.Dsl.optionsOrNull: com.google.protobuf.DescriptorProtos.MethodOptions?
      get() = _builder.optionsOrNull

    /**
     * <code>optional bool client_streaming = 5 [default = false, json_name = "clientStreaming"];</code>
     */
    public var clientStreaming: kotlin.Boolean
      @JvmName("getClientStreaming")
      get() = _builder.clientStreaming
      @JvmName("setClientStreaming")
      set(value) {
        _builder.clientStreaming = value
      }
    /**
     * `optional bool client_streaming = 5 [default = false, json_name = "clientStreaming"];`
     */
    public fun clearClientStreaming() {
      _builder.clearClientStreaming()
    }
    /**
     * `optional bool client_streaming = 5 [default = false, json_name = "clientStreaming"];`
     * @return Whether the clientStreaming field is set.
     */
    public fun hasClientStreaming(): kotlin.Boolean {
      return _builder.hasClientStreaming()
    }

    /**
     * <code>optional bool server_streaming = 6 [default = false, json_name = "serverStreaming"];</code>
     */
    public var serverStreaming: kotlin.Boolean
      @JvmName("getServerStreaming")
      get() = _builder.serverStreaming
      @JvmName("setServerStreaming")
      set(value) {
        _builder.serverStreaming = value
      }
    /**
     * `optional bool server_streaming = 6 [default = false, json_name = "serverStreaming"];`
     */
    public fun clearServerStreaming() {
      _builder.clearServerStreaming()
    }
    /**
     * `optional bool server_streaming = 6 [default = false, json_name = "serverStreaming"];`
     * @return Whether the serverStreaming field is set.
     */
    public fun hasServerStreaming(): kotlin.Boolean {
      return _builder.hasServerStreaming()
    }
  }
}
public inline fun com.google.protobuf.DescriptorProtos.MethodDescriptorProto.copy(block: `com.google.protobuf`.MethodDescriptorProtoKt.Dsl.() -> kotlin.Unit): com.google.protobuf.DescriptorProtos.MethodDescriptorProto =
  `com.google.protobuf`.MethodDescriptorProtoKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.google.protobuf.DescriptorProtos.MethodDescriptorProtoOrBuilder.optionsOrNull: com.google.protobuf.DescriptorProtos.MethodOptions?
  get() = if (hasOptions()) getOptions() else null

