// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/protobuf/api.proto
// Protobuf Java Version: 4.28.3

package com.google.protobuf;

/**
 * Protobuf type {@code google.protobuf.Method}
 */
public  final class Method extends
    com.google.protobuf.GeneratedMessageLite<
        Method, Method.Builder> implements
    // @@protoc_insertion_point(message_implements:google.protobuf.Method)
    MethodOrBuilder {
  private Method() {
    name_ = "";
    requestTypeUrl_ = "";
    responseTypeUrl_ = "";
    options_ = emptyProtobufList();
  }
  public static final int NAME_FIELD_NUMBER = 1;
  private java.lang.String name_;
  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    return name_;
  }
  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(name_);
  }
  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @param value The name to set.
   */
  private void setName(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    name_ = value;
  }
  /**
   * <code>string name = 1 [json_name = "name"];</code>
   */
  private void clearName() {

    name_ = getDefaultInstance().getName();
  }
  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @param value The bytes for name to set.
   */
  private void setNameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    name_ = value.toStringUtf8();

  }

  public static final int REQUEST_TYPE_URL_FIELD_NUMBER = 2;
  private java.lang.String requestTypeUrl_;
  /**
   * <code>string request_type_url = 2 [json_name = "requestTypeUrl"];</code>
   * @return The requestTypeUrl.
   */
  @java.lang.Override
  public java.lang.String getRequestTypeUrl() {
    return requestTypeUrl_;
  }
  /**
   * <code>string request_type_url = 2 [json_name = "requestTypeUrl"];</code>
   * @return The bytes for requestTypeUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRequestTypeUrlBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(requestTypeUrl_);
  }
  /**
   * <code>string request_type_url = 2 [json_name = "requestTypeUrl"];</code>
   * @param value The requestTypeUrl to set.
   */
  private void setRequestTypeUrl(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    requestTypeUrl_ = value;
  }
  /**
   * <code>string request_type_url = 2 [json_name = "requestTypeUrl"];</code>
   */
  private void clearRequestTypeUrl() {

    requestTypeUrl_ = getDefaultInstance().getRequestTypeUrl();
  }
  /**
   * <code>string request_type_url = 2 [json_name = "requestTypeUrl"];</code>
   * @param value The bytes for requestTypeUrl to set.
   */
  private void setRequestTypeUrlBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    requestTypeUrl_ = value.toStringUtf8();

  }

  public static final int REQUEST_STREAMING_FIELD_NUMBER = 3;
  private boolean requestStreaming_;
  /**
   * <code>bool request_streaming = 3 [json_name = "requestStreaming"];</code>
   * @return The requestStreaming.
   */
  @java.lang.Override
  public boolean getRequestStreaming() {
    return requestStreaming_;
  }
  /**
   * <code>bool request_streaming = 3 [json_name = "requestStreaming"];</code>
   * @param value The requestStreaming to set.
   */
  private void setRequestStreaming(boolean value) {
    
    requestStreaming_ = value;
  }
  /**
   * <code>bool request_streaming = 3 [json_name = "requestStreaming"];</code>
   */
  private void clearRequestStreaming() {

    requestStreaming_ = false;
  }

  public static final int RESPONSE_TYPE_URL_FIELD_NUMBER = 4;
  private java.lang.String responseTypeUrl_;
  /**
   * <code>string response_type_url = 4 [json_name = "responseTypeUrl"];</code>
   * @return The responseTypeUrl.
   */
  @java.lang.Override
  public java.lang.String getResponseTypeUrl() {
    return responseTypeUrl_;
  }
  /**
   * <code>string response_type_url = 4 [json_name = "responseTypeUrl"];</code>
   * @return The bytes for responseTypeUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getResponseTypeUrlBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(responseTypeUrl_);
  }
  /**
   * <code>string response_type_url = 4 [json_name = "responseTypeUrl"];</code>
   * @param value The responseTypeUrl to set.
   */
  private void setResponseTypeUrl(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    responseTypeUrl_ = value;
  }
  /**
   * <code>string response_type_url = 4 [json_name = "responseTypeUrl"];</code>
   */
  private void clearResponseTypeUrl() {

    responseTypeUrl_ = getDefaultInstance().getResponseTypeUrl();
  }
  /**
   * <code>string response_type_url = 4 [json_name = "responseTypeUrl"];</code>
   * @param value The bytes for responseTypeUrl to set.
   */
  private void setResponseTypeUrlBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    responseTypeUrl_ = value.toStringUtf8();

  }

  public static final int RESPONSE_STREAMING_FIELD_NUMBER = 5;
  private boolean responseStreaming_;
  /**
   * <code>bool response_streaming = 5 [json_name = "responseStreaming"];</code>
   * @return The responseStreaming.
   */
  @java.lang.Override
  public boolean getResponseStreaming() {
    return responseStreaming_;
  }
  /**
   * <code>bool response_streaming = 5 [json_name = "responseStreaming"];</code>
   * @param value The responseStreaming to set.
   */
  private void setResponseStreaming(boolean value) {
    
    responseStreaming_ = value;
  }
  /**
   * <code>bool response_streaming = 5 [json_name = "responseStreaming"];</code>
   */
  private void clearResponseStreaming() {

    responseStreaming_ = false;
  }

  public static final int OPTIONS_FIELD_NUMBER = 6;
  private com.google.protobuf.Internal.ProtobufList<com.google.protobuf.Option> options_;
  /**
   * <code>repeated .google.protobuf.Option options = 6 [json_name = "options"];</code>
   */
  @java.lang.Override
  public java.util.List<com.google.protobuf.Option> getOptionsList() {
    return options_;
  }
  /**
   * <code>repeated .google.protobuf.Option options = 6 [json_name = "options"];</code>
   */
  public java.util.List<? extends com.google.protobuf.OptionOrBuilder> 
      getOptionsOrBuilderList() {
    return options_;
  }
  /**
   * <code>repeated .google.protobuf.Option options = 6 [json_name = "options"];</code>
   */
  @java.lang.Override
  public int getOptionsCount() {
    return options_.size();
  }
  /**
   * <code>repeated .google.protobuf.Option options = 6 [json_name = "options"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.Option getOptions(int index) {
    return options_.get(index);
  }
  /**
   * <code>repeated .google.protobuf.Option options = 6 [json_name = "options"];</code>
   */
  public com.google.protobuf.OptionOrBuilder getOptionsOrBuilder(
      int index) {
    return options_.get(index);
  }
  private void ensureOptionsIsMutable() {
    com.google.protobuf.Internal.ProtobufList<com.google.protobuf.Option> tmp = options_;
    if (!tmp.isModifiable()) {
      options_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .google.protobuf.Option options = 6 [json_name = "options"];</code>
   */
  private void setOptions(
      int index, com.google.protobuf.Option value) {
    value.getClass();
  ensureOptionsIsMutable();
    options_.set(index, value);
  }
  /**
   * <code>repeated .google.protobuf.Option options = 6 [json_name = "options"];</code>
   */
  private void addOptions(com.google.protobuf.Option value) {
    value.getClass();
  ensureOptionsIsMutable();
    options_.add(value);
  }
  /**
   * <code>repeated .google.protobuf.Option options = 6 [json_name = "options"];</code>
   */
  private void addOptions(
      int index, com.google.protobuf.Option value) {
    value.getClass();
  ensureOptionsIsMutable();
    options_.add(index, value);
  }
  /**
   * <code>repeated .google.protobuf.Option options = 6 [json_name = "options"];</code>
   */
  private void addAllOptions(
      java.lang.Iterable<? extends com.google.protobuf.Option> values) {
    ensureOptionsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, options_);
  }
  /**
   * <code>repeated .google.protobuf.Option options = 6 [json_name = "options"];</code>
   */
  private void clearOptions() {
    options_ = emptyProtobufList();
  }
  /**
   * <code>repeated .google.protobuf.Option options = 6 [json_name = "options"];</code>
   */
  private void removeOptions(int index) {
    ensureOptionsIsMutable();
    options_.remove(index);
  }

  public static final int SYNTAX_FIELD_NUMBER = 7;
  private int syntax_;
  /**
   * <code>.google.protobuf.Syntax syntax = 7 [json_name = "syntax"];</code>
   * @return The enum numeric value on the wire for syntax.
   */
  @java.lang.Override
  public int getSyntaxValue() {
    return syntax_;
  }
  /**
   * <code>.google.protobuf.Syntax syntax = 7 [json_name = "syntax"];</code>
   * @return The syntax.
   */
  @java.lang.Override
  public com.google.protobuf.Syntax getSyntax() {
    com.google.protobuf.Syntax result = com.google.protobuf.Syntax.forNumber(syntax_);
    return result == null ? com.google.protobuf.Syntax.UNRECOGNIZED : result;
  }
  /**
   * <code>.google.protobuf.Syntax syntax = 7 [json_name = "syntax"];</code>
   * @param value The enum numeric value on the wire for syntax to set.
   */
  private void setSyntaxValue(int value) {
      syntax_ = value;
  }
  /**
   * <code>.google.protobuf.Syntax syntax = 7 [json_name = "syntax"];</code>
   * @param value The syntax to set.
   */
  private void setSyntax(com.google.protobuf.Syntax value) {
    syntax_ = value.getNumber();

  }
  /**
   * <code>.google.protobuf.Syntax syntax = 7 [json_name = "syntax"];</code>
   */
  private void clearSyntax() {

    syntax_ = 0;
  }

  public static com.google.protobuf.Method parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.google.protobuf.Method parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.google.protobuf.Method parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.google.protobuf.Method parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.google.protobuf.Method parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.google.protobuf.Method parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.google.protobuf.Method parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.google.protobuf.Method parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.google.protobuf.Method parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.google.protobuf.Method parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.google.protobuf.Method parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.google.protobuf.Method parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.google.protobuf.Method prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code google.protobuf.Method}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.google.protobuf.Method, Builder> implements
      // @@protoc_insertion_point(builder_implements:google.protobuf.Method)
      com.google.protobuf.MethodOrBuilder {
    // Construct using com.google.protobuf.Method.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string name = 1 [json_name = "name"];</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      return instance.getName();
    }
    /**
     * <code>string name = 1 [json_name = "name"];</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      return instance.getNameBytes();
    }
    /**
     * <code>string name = 1 [json_name = "name"];</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      copyOnWrite();
      instance.setName(value);
      return this;
    }
    /**
     * <code>string name = 1 [json_name = "name"];</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      copyOnWrite();
      instance.clearName();
      return this;
    }
    /**
     * <code>string name = 1 [json_name = "name"];</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setNameBytes(value);
      return this;
    }

    /**
     * <code>string request_type_url = 2 [json_name = "requestTypeUrl"];</code>
     * @return The requestTypeUrl.
     */
    @java.lang.Override
    public java.lang.String getRequestTypeUrl() {
      return instance.getRequestTypeUrl();
    }
    /**
     * <code>string request_type_url = 2 [json_name = "requestTypeUrl"];</code>
     * @return The bytes for requestTypeUrl.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRequestTypeUrlBytes() {
      return instance.getRequestTypeUrlBytes();
    }
    /**
     * <code>string request_type_url = 2 [json_name = "requestTypeUrl"];</code>
     * @param value The requestTypeUrl to set.
     * @return This builder for chaining.
     */
    public Builder setRequestTypeUrl(
        java.lang.String value) {
      copyOnWrite();
      instance.setRequestTypeUrl(value);
      return this;
    }
    /**
     * <code>string request_type_url = 2 [json_name = "requestTypeUrl"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestTypeUrl() {
      copyOnWrite();
      instance.clearRequestTypeUrl();
      return this;
    }
    /**
     * <code>string request_type_url = 2 [json_name = "requestTypeUrl"];</code>
     * @param value The bytes for requestTypeUrl to set.
     * @return This builder for chaining.
     */
    public Builder setRequestTypeUrlBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setRequestTypeUrlBytes(value);
      return this;
    }

    /**
     * <code>bool request_streaming = 3 [json_name = "requestStreaming"];</code>
     * @return The requestStreaming.
     */
    @java.lang.Override
    public boolean getRequestStreaming() {
      return instance.getRequestStreaming();
    }
    /**
     * <code>bool request_streaming = 3 [json_name = "requestStreaming"];</code>
     * @param value The requestStreaming to set.
     * @return This builder for chaining.
     */
    public Builder setRequestStreaming(boolean value) {
      copyOnWrite();
      instance.setRequestStreaming(value);
      return this;
    }
    /**
     * <code>bool request_streaming = 3 [json_name = "requestStreaming"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestStreaming() {
      copyOnWrite();
      instance.clearRequestStreaming();
      return this;
    }

    /**
     * <code>string response_type_url = 4 [json_name = "responseTypeUrl"];</code>
     * @return The responseTypeUrl.
     */
    @java.lang.Override
    public java.lang.String getResponseTypeUrl() {
      return instance.getResponseTypeUrl();
    }
    /**
     * <code>string response_type_url = 4 [json_name = "responseTypeUrl"];</code>
     * @return The bytes for responseTypeUrl.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getResponseTypeUrlBytes() {
      return instance.getResponseTypeUrlBytes();
    }
    /**
     * <code>string response_type_url = 4 [json_name = "responseTypeUrl"];</code>
     * @param value The responseTypeUrl to set.
     * @return This builder for chaining.
     */
    public Builder setResponseTypeUrl(
        java.lang.String value) {
      copyOnWrite();
      instance.setResponseTypeUrl(value);
      return this;
    }
    /**
     * <code>string response_type_url = 4 [json_name = "responseTypeUrl"];</code>
     * @return This builder for chaining.
     */
    public Builder clearResponseTypeUrl() {
      copyOnWrite();
      instance.clearResponseTypeUrl();
      return this;
    }
    /**
     * <code>string response_type_url = 4 [json_name = "responseTypeUrl"];</code>
     * @param value The bytes for responseTypeUrl to set.
     * @return This builder for chaining.
     */
    public Builder setResponseTypeUrlBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setResponseTypeUrlBytes(value);
      return this;
    }

    /**
     * <code>bool response_streaming = 5 [json_name = "responseStreaming"];</code>
     * @return The responseStreaming.
     */
    @java.lang.Override
    public boolean getResponseStreaming() {
      return instance.getResponseStreaming();
    }
    /**
     * <code>bool response_streaming = 5 [json_name = "responseStreaming"];</code>
     * @param value The responseStreaming to set.
     * @return This builder for chaining.
     */
    public Builder setResponseStreaming(boolean value) {
      copyOnWrite();
      instance.setResponseStreaming(value);
      return this;
    }
    /**
     * <code>bool response_streaming = 5 [json_name = "responseStreaming"];</code>
     * @return This builder for chaining.
     */
    public Builder clearResponseStreaming() {
      copyOnWrite();
      instance.clearResponseStreaming();
      return this;
    }

    /**
     * <code>repeated .google.protobuf.Option options = 6 [json_name = "options"];</code>
     */
    @java.lang.Override
    public java.util.List<com.google.protobuf.Option> getOptionsList() {
      return java.util.Collections.unmodifiableList(
          instance.getOptionsList());
    }
    /**
     * <code>repeated .google.protobuf.Option options = 6 [json_name = "options"];</code>
     */
    @java.lang.Override
    public int getOptionsCount() {
      return instance.getOptionsCount();
    }/**
     * <code>repeated .google.protobuf.Option options = 6 [json_name = "options"];</code>
     */
    @java.lang.Override
    public com.google.protobuf.Option getOptions(int index) {
      return instance.getOptions(index);
    }
    /**
     * <code>repeated .google.protobuf.Option options = 6 [json_name = "options"];</code>
     */
    public Builder setOptions(
        int index, com.google.protobuf.Option value) {
      copyOnWrite();
      instance.setOptions(index, value);
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Option options = 6 [json_name = "options"];</code>
     */
    public Builder setOptions(
        int index, com.google.protobuf.Option.Builder builderForValue) {
      copyOnWrite();
      instance.setOptions(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Option options = 6 [json_name = "options"];</code>
     */
    public Builder addOptions(com.google.protobuf.Option value) {
      copyOnWrite();
      instance.addOptions(value);
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Option options = 6 [json_name = "options"];</code>
     */
    public Builder addOptions(
        int index, com.google.protobuf.Option value) {
      copyOnWrite();
      instance.addOptions(index, value);
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Option options = 6 [json_name = "options"];</code>
     */
    public Builder addOptions(
        com.google.protobuf.Option.Builder builderForValue) {
      copyOnWrite();
      instance.addOptions(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Option options = 6 [json_name = "options"];</code>
     */
    public Builder addOptions(
        int index, com.google.protobuf.Option.Builder builderForValue) {
      copyOnWrite();
      instance.addOptions(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Option options = 6 [json_name = "options"];</code>
     */
    public Builder addAllOptions(
        java.lang.Iterable<? extends com.google.protobuf.Option> values) {
      copyOnWrite();
      instance.addAllOptions(values);
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Option options = 6 [json_name = "options"];</code>
     */
    public Builder clearOptions() {
      copyOnWrite();
      instance.clearOptions();
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Option options = 6 [json_name = "options"];</code>
     */
    public Builder removeOptions(int index) {
      copyOnWrite();
      instance.removeOptions(index);
      return this;
    }

    /**
     * <code>.google.protobuf.Syntax syntax = 7 [json_name = "syntax"];</code>
     * @return The enum numeric value on the wire for syntax.
     */
    @java.lang.Override
    public int getSyntaxValue() {
      return instance.getSyntaxValue();
    }
    /**
     * <code>.google.protobuf.Syntax syntax = 7 [json_name = "syntax"];</code>
     * @param value The syntax to set.
     * @return This builder for chaining.
     */
    public Builder setSyntaxValue(int value) {
      copyOnWrite();
      instance.setSyntaxValue(value);
      return this;
    }
    /**
     * <code>.google.protobuf.Syntax syntax = 7 [json_name = "syntax"];</code>
     * @return The syntax.
     */
    @java.lang.Override
    public com.google.protobuf.Syntax getSyntax() {
      return instance.getSyntax();
    }
    /**
     * <code>.google.protobuf.Syntax syntax = 7 [json_name = "syntax"];</code>
     * @param value The enum numeric value on the wire for syntax to set.
     * @return This builder for chaining.
     */
    public Builder setSyntax(com.google.protobuf.Syntax value) {
      copyOnWrite();
      instance.setSyntax(value);
      return this;
    }
    /**
     * <code>.google.protobuf.Syntax syntax = 7 [json_name = "syntax"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSyntax() {
      copyOnWrite();
      instance.clearSyntax();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:google.protobuf.Method)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.google.protobuf.Method();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "name_",
            "requestTypeUrl_",
            "requestStreaming_",
            "responseTypeUrl_",
            "responseStreaming_",
            "options_",
            com.google.protobuf.Option.class,
            "syntax_",
          };
          java.lang.String info =
              "\u0000\u0007\u0000\u0000\u0001\u0007\u0007\u0000\u0001\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u0007\u0004\u0208\u0005\u0007\u0006\u001b\u0007\f";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.google.protobuf.Method> parser = PARSER;
        if (parser == null) {
          synchronized (com.google.protobuf.Method.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.google.protobuf.Method>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:google.protobuf.Method)
  private static final com.google.protobuf.Method DEFAULT_INSTANCE;
  static {
    Method defaultInstance = new Method();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Method.class, defaultInstance);
  }

  public static com.google.protobuf.Method getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Method> PARSER;

  public static com.google.protobuf.Parser<Method> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

