// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/protobuf/api.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.google.protobuf;

@kotlin.jvm.JvmName("-initializemixin")
public inline fun mixin(block: com.google.protobuf.MixinKt.Dsl.() -> kotlin.Unit): com.google.protobuf.Mixin =
  com.google.protobuf.MixinKt.Dsl._create(com.google.protobuf.Mixin.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `google.protobuf.Mixin`
 */
public object MixinKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.google.protobuf.Mixin.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.google.protobuf.Mixin.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.google.protobuf.Mixin = _builder.build()

    /**
     * `string name = 1 [json_name = "name"];`
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.name
      @JvmName("setName")
      set(value) {
        _builder.name = value
      }
    /**
     * `string name = 1 [json_name = "name"];`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * `string root = 2 [json_name = "root"];`
     */
    public var root: kotlin.String
      @JvmName("getRoot")
      get() = _builder.root
      @JvmName("setRoot")
      set(value) {
        _builder.root = value
      }
    /**
     * `string root = 2 [json_name = "root"];`
     */
    public fun clearRoot() {
      _builder.clearRoot()
    }
  }
}
public inline fun com.google.protobuf.Mixin.copy(block: `com.google.protobuf`.MixinKt.Dsl.() -> kotlin.Unit): com.google.protobuf.Mixin =
  `com.google.protobuf`.MixinKt.Dsl._create(this.toBuilder()).apply { block() }._build()

