// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/protobuf/source_context.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.google.protobuf;

@kotlin.jvm.JvmName("-initializesourceContext")
public inline fun sourceContext(block: com.google.protobuf.SourceContextKt.Dsl.() -> kotlin.Unit): com.google.protobuf.SourceContext =
  com.google.protobuf.SourceContextKt.Dsl._create(com.google.protobuf.SourceContext.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `google.protobuf.SourceContext`
 */
public object SourceContextKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.google.protobuf.SourceContext.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.google.protobuf.SourceContext.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.google.protobuf.SourceContext = _builder.build()

    /**
     * `string file_name = 1 [json_name = "fileName"];`
     */
    public var fileName: kotlin.String
      @JvmName("getFileName")
      get() = _builder.fileName
      @JvmName("setFileName")
      set(value) {
        _builder.fileName = value
      }
    /**
     * `string file_name = 1 [json_name = "fileName"];`
     */
    public fun clearFileName() {
      _builder.clearFileName()
    }
  }
}
public inline fun com.google.protobuf.SourceContext.copy(block: `com.google.protobuf`.SourceContextKt.Dsl.() -> kotlin.Unit): com.google.protobuf.SourceContext =
  `com.google.protobuf`.SourceContextKt.Dsl._create(this.toBuilder()).apply { block() }._build()

