// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/protobuf/descriptor.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.google.protobuf;

@kotlin.jvm.JvmName("-initializesourceCodeInfo")
public inline fun sourceCodeInfo(block: com.google.protobuf.SourceCodeInfoKt.Dsl.() -> kotlin.Unit): com.google.protobuf.DescriptorProtos.SourceCodeInfo =
  com.google.protobuf.SourceCodeInfoKt.Dsl._create(com.google.protobuf.DescriptorProtos.SourceCodeInfo.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `google.protobuf.SourceCodeInfo`
 */
public object SourceCodeInfoKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.google.protobuf.DescriptorProtos.SourceCodeInfo.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.google.protobuf.DescriptorProtos.SourceCodeInfo.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.google.protobuf.DescriptorProtos.SourceCodeInfo = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class LocationProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .google.protobuf.SourceCodeInfo.Location location = 1 [json_name = "location"];`
     */
     public val location: com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.SourceCodeInfo.Location, LocationProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.locationList
      )
    /**
     * `repeated .google.protobuf.SourceCodeInfo.Location location = 1 [json_name = "location"];`
     * @param value The location to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addLocation")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.SourceCodeInfo.Location, LocationProxy>.add(value: com.google.protobuf.DescriptorProtos.SourceCodeInfo.Location) {
      _builder.addLocation(value)
    }
    /**
     * `repeated .google.protobuf.SourceCodeInfo.Location location = 1 [json_name = "location"];`
     * @param value The location to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignLocation")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.SourceCodeInfo.Location, LocationProxy>.plusAssign(value: com.google.protobuf.DescriptorProtos.SourceCodeInfo.Location) {
      add(value)
    }
    /**
     * `repeated .google.protobuf.SourceCodeInfo.Location location = 1 [json_name = "location"];`
     * @param values The location to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllLocation")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.SourceCodeInfo.Location, LocationProxy>.addAll(values: kotlin.collections.Iterable<com.google.protobuf.DescriptorProtos.SourceCodeInfo.Location>) {
      _builder.addAllLocation(values)
    }
    /**
     * `repeated .google.protobuf.SourceCodeInfo.Location location = 1 [json_name = "location"];`
     * @param values The location to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllLocation")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.SourceCodeInfo.Location, LocationProxy>.plusAssign(values: kotlin.collections.Iterable<com.google.protobuf.DescriptorProtos.SourceCodeInfo.Location>) {
      addAll(values)
    }
    /**
     * `repeated .google.protobuf.SourceCodeInfo.Location location = 1 [json_name = "location"];`
     * @param index The index to set the value at.
     * @param value The location to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setLocation")
    public operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.SourceCodeInfo.Location, LocationProxy>.set(index: kotlin.Int, value: com.google.protobuf.DescriptorProtos.SourceCodeInfo.Location) {
      _builder.setLocation(index, value)
    }
    /**
     * `repeated .google.protobuf.SourceCodeInfo.Location location = 1 [json_name = "location"];`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearLocation")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.SourceCodeInfo.Location, LocationProxy>.clear() {
      _builder.clearLocation()
    }
  }
  @kotlin.jvm.JvmName("-initializelocation")
  public inline fun location(block: com.google.protobuf.SourceCodeInfoKt.LocationKt.Dsl.() -> kotlin.Unit): com.google.protobuf.DescriptorProtos.SourceCodeInfo.Location =
    com.google.protobuf.SourceCodeInfoKt.LocationKt.Dsl._create(com.google.protobuf.DescriptorProtos.SourceCodeInfo.Location.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `google.protobuf.SourceCodeInfo.Location`
   */
  public object LocationKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: com.google.protobuf.DescriptorProtos.SourceCodeInfo.Location.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _create(builder: com.google.protobuf.DescriptorProtos.SourceCodeInfo.Location.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _build(): com.google.protobuf.DescriptorProtos.SourceCodeInfo.Location = _builder.build()

      /**
       * An uninstantiable, behaviorless type to represent the field in
       * generics.
       */
      @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      public class PathProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
      /**
       * <code>repeated int32 path = 1 [json_name = "path", packed = true];</code>
       */
       public val path: com.google.protobuf.kotlin.DslList<kotlin.Int, PathProxy>
        @kotlin.jvm.JvmSynthetic
        get() = com.google.protobuf.kotlin.DslList(
          _builder.pathList
        )
      /**
       * `repeated int32 path = 1 [json_name = "path", packed = true];`
       * @param value The path to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("addPath")
      public fun com.google.protobuf.kotlin.DslList<kotlin.Int, PathProxy>.add(value: kotlin.Int) {
        _builder.addPath(value)
      }/**
       * `repeated int32 path = 1 [json_name = "path", packed = true];`
       * @param value The path to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("plusAssignPath")
      @Suppress("NOTHING_TO_INLINE")
      public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Int, PathProxy>.plusAssign(value: kotlin.Int) {
        add(value)
      }/**
       * `repeated int32 path = 1 [json_name = "path", packed = true];`
       * @param values The path to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("addAllPath")
      public fun com.google.protobuf.kotlin.DslList<kotlin.Int, PathProxy>.addAll(values: kotlin.collections.Iterable<kotlin.Int>) {
        _builder.addAllPath(values)
      }/**
       * `repeated int32 path = 1 [json_name = "path", packed = true];`
       * @param values The path to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("plusAssignAllPath")
      @Suppress("NOTHING_TO_INLINE")
      public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Int, PathProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.Int>) {
        addAll(values)
      }/**
       * `repeated int32 path = 1 [json_name = "path", packed = true];`
       * @param index The index to set the value at.
       * @param value The path to set.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("setPath")
      public operator fun com.google.protobuf.kotlin.DslList<kotlin.Int, PathProxy>.set(index: kotlin.Int, value: kotlin.Int) {
        _builder.setPath(index, value)
      }/**
       * `repeated int32 path = 1 [json_name = "path", packed = true];`
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("clearPath")
      public fun com.google.protobuf.kotlin.DslList<kotlin.Int, PathProxy>.clear() {
        _builder.clearPath()
      }
      /**
       * An uninstantiable, behaviorless type to represent the field in
       * generics.
       */
      @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      public class SpanProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
      /**
       * <code>repeated int32 span = 2 [json_name = "span", packed = true];</code>
       */
       public val span: com.google.protobuf.kotlin.DslList<kotlin.Int, SpanProxy>
        @kotlin.jvm.JvmSynthetic
        get() = com.google.protobuf.kotlin.DslList(
          _builder.spanList
        )
      /**
       * `repeated int32 span = 2 [json_name = "span", packed = true];`
       * @param value The span to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("addSpan")
      public fun com.google.protobuf.kotlin.DslList<kotlin.Int, SpanProxy>.add(value: kotlin.Int) {
        _builder.addSpan(value)
      }/**
       * `repeated int32 span = 2 [json_name = "span", packed = true];`
       * @param value The span to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("plusAssignSpan")
      @Suppress("NOTHING_TO_INLINE")
      public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Int, SpanProxy>.plusAssign(value: kotlin.Int) {
        add(value)
      }/**
       * `repeated int32 span = 2 [json_name = "span", packed = true];`
       * @param values The span to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("addAllSpan")
      public fun com.google.protobuf.kotlin.DslList<kotlin.Int, SpanProxy>.addAll(values: kotlin.collections.Iterable<kotlin.Int>) {
        _builder.addAllSpan(values)
      }/**
       * `repeated int32 span = 2 [json_name = "span", packed = true];`
       * @param values The span to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("plusAssignAllSpan")
      @Suppress("NOTHING_TO_INLINE")
      public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Int, SpanProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.Int>) {
        addAll(values)
      }/**
       * `repeated int32 span = 2 [json_name = "span", packed = true];`
       * @param index The index to set the value at.
       * @param value The span to set.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("setSpan")
      public operator fun com.google.protobuf.kotlin.DslList<kotlin.Int, SpanProxy>.set(index: kotlin.Int, value: kotlin.Int) {
        _builder.setSpan(index, value)
      }/**
       * `repeated int32 span = 2 [json_name = "span", packed = true];`
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("clearSpan")
      public fun com.google.protobuf.kotlin.DslList<kotlin.Int, SpanProxy>.clear() {
        _builder.clearSpan()
      }
      /**
       * `optional string leading_comments = 3 [json_name = "leadingComments"];`
       */
      public var leadingComments: kotlin.String
        @JvmName("getLeadingComments")
        get() = _builder.leadingComments
        @JvmName("setLeadingComments")
        set(value) {
          _builder.leadingComments = value
        }
      /**
       * `optional string leading_comments = 3 [json_name = "leadingComments"];`
       */
      public fun clearLeadingComments() {
        _builder.clearLeadingComments()
      }
      /**
       * `optional string leading_comments = 3 [json_name = "leadingComments"];`
       * @return Whether the leadingComments field is set.
       */
      public fun hasLeadingComments(): kotlin.Boolean {
        return _builder.hasLeadingComments()
      }

      /**
       * `optional string trailing_comments = 4 [json_name = "trailingComments"];`
       */
      public var trailingComments: kotlin.String
        @JvmName("getTrailingComments")
        get() = _builder.trailingComments
        @JvmName("setTrailingComments")
        set(value) {
          _builder.trailingComments = value
        }
      /**
       * `optional string trailing_comments = 4 [json_name = "trailingComments"];`
       */
      public fun clearTrailingComments() {
        _builder.clearTrailingComments()
      }
      /**
       * `optional string trailing_comments = 4 [json_name = "trailingComments"];`
       * @return Whether the trailingComments field is set.
       */
      public fun hasTrailingComments(): kotlin.Boolean {
        return _builder.hasTrailingComments()
      }

      /**
       * An uninstantiable, behaviorless type to represent the field in
       * generics.
       */
      @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      public class LeadingDetachedCommentsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
      /**
       * `repeated string leading_detached_comments = 6 [json_name = "leadingDetachedComments"];`
       * @return A list containing the leadingDetachedComments.
       */
      public val leadingDetachedComments: com.google.protobuf.kotlin.DslList<kotlin.String, LeadingDetachedCommentsProxy>
      @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
        get() = com.google.protobuf.kotlin.DslList(
          _builder.leadingDetachedCommentsList
        )
      /**
       * `repeated string leading_detached_comments = 6 [json_name = "leadingDetachedComments"];`
       * @param value The leadingDetachedComments to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("addLeadingDetachedComments")
      public fun com.google.protobuf.kotlin.DslList<kotlin.String, LeadingDetachedCommentsProxy>.add(value: kotlin.String) {
        _builder.addLeadingDetachedComments(value)
      }
      /**
       * `repeated string leading_detached_comments = 6 [json_name = "leadingDetachedComments"];`
       * @param value The leadingDetachedComments to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("plusAssignLeadingDetachedComments")
      @Suppress("NOTHING_TO_INLINE")
      public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, LeadingDetachedCommentsProxy>.plusAssign(value: kotlin.String) {
        add(value)
      }
      /**
       * `repeated string leading_detached_comments = 6 [json_name = "leadingDetachedComments"];`
       * @param values The leadingDetachedComments to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("addAllLeadingDetachedComments")
      public fun com.google.protobuf.kotlin.DslList<kotlin.String, LeadingDetachedCommentsProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
        _builder.addAllLeadingDetachedComments(values)
      }
      /**
       * `repeated string leading_detached_comments = 6 [json_name = "leadingDetachedComments"];`
       * @param values The leadingDetachedComments to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("plusAssignAllLeadingDetachedComments")
      @Suppress("NOTHING_TO_INLINE")
      public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, LeadingDetachedCommentsProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
        addAll(values)
      }
      /**
       * `repeated string leading_detached_comments = 6 [json_name = "leadingDetachedComments"];`
       * @param index The index to set the value at.
       * @param value The leadingDetachedComments to set.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("setLeadingDetachedComments")
      public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, LeadingDetachedCommentsProxy>.set(index: kotlin.Int, value: kotlin.String) {
        _builder.setLeadingDetachedComments(index, value)
      }/**
       * `repeated string leading_detached_comments = 6 [json_name = "leadingDetachedComments"];`
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("clearLeadingDetachedComments")
      public fun com.google.protobuf.kotlin.DslList<kotlin.String, LeadingDetachedCommentsProxy>.clear() {
        _builder.clearLeadingDetachedComments()
      }}
  }
}
public inline fun com.google.protobuf.DescriptorProtos.SourceCodeInfo.copy(block: `com.google.protobuf`.SourceCodeInfoKt.Dsl.() -> kotlin.Unit): com.google.protobuf.DescriptorProtos.SourceCodeInfo =
  `com.google.protobuf`.SourceCodeInfoKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public inline fun com.google.protobuf.DescriptorProtos.SourceCodeInfo.Location.copy(block: `com.google.protobuf`.SourceCodeInfoKt.LocationKt.Dsl.() -> kotlin.Unit): com.google.protobuf.DescriptorProtos.SourceCodeInfo.Location =
  `com.google.protobuf`.SourceCodeInfoKt.LocationKt.Dsl._create(this.toBuilder()).apply { block() }._build()

