// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/protobuf/source_context.proto
// Protobuf Java Version: 4.28.3

package com.google.protobuf;

public interface SourceContextOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.protobuf.SourceContext)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string file_name = 1 [json_name = "fileName"];</code>
   * @return The fileName.
   */
  java.lang.String getFileName();
  /**
   * <code>string file_name = 1 [json_name = "fileName"];</code>
   * @return The bytes for fileName.
   */
  com.google.protobuf.ByteString
      getFileNameBytes();
}
