// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/protobuf/wrappers.proto
// Protobuf Java Version: 4.28.3

package com.google.protobuf;

public interface StringValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.protobuf.StringValue)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string value = 1 [json_name = "value"];</code>
   * @return The value.
   */
  java.lang.String getValue();
  /**
   * <code>string value = 1 [json_name = "value"];</code>
   * @return The bytes for value.
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
