// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/protobuf/struct.proto
// Protobuf Java Version: 4.28.3

package com.google.protobuf;

public interface StructOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.protobuf.Struct)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>map&lt;string, .google.protobuf.Value&gt; fields = 1 [json_name = "fields"];</code>
   */
  int getFieldsCount();
  /**
   * <code>map&lt;string, .google.protobuf.Value&gt; fields = 1 [json_name = "fields"];</code>
   */
  boolean containsFields(
      java.lang.String key);
  /**
   * Use {@link #getFieldsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, com.google.protobuf.Value>
  getFields();
  /**
   * <code>map&lt;string, .google.protobuf.Value&gt; fields = 1 [json_name = "fields"];</code>
   */
  java.util.Map<java.lang.String, com.google.protobuf.Value>
  getFieldsMap();
  /**
   * <code>map&lt;string, .google.protobuf.Value&gt; fields = 1 [json_name = "fields"];</code>
   */

  /* nullable */
com.google.protobuf.Value getFieldsOrDefault(
      java.lang.String key,
      /* nullable */
com.google.protobuf.Value defaultValue);
  /**
   * <code>map&lt;string, .google.protobuf.Value&gt; fields = 1 [json_name = "fields"];</code>
   */

  com.google.protobuf.Value getFieldsOrThrow(
      java.lang.String key);
}
