// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/protobuf/type.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.google.protobuf;

@kotlin.jvm.JvmName("-initializetype")
public inline fun type(block: com.google.protobuf.TypeKt.Dsl.() -> kotlin.Unit): com.google.protobuf.Type =
  com.google.protobuf.TypeKt.Dsl._create(com.google.protobuf.Type.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `google.protobuf.Type`
 */
public object TypeKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.google.protobuf.Type.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.google.protobuf.Type.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.google.protobuf.Type = _builder.build()

    /**
     * `string name = 1 [json_name = "name"];`
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.name
      @JvmName("setName")
      set(value) {
        _builder.name = value
      }
    /**
     * `string name = 1 [json_name = "name"];`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class FieldsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .google.protobuf.Field fields = 2 [json_name = "fields"];`
     */
     public val fields: com.google.protobuf.kotlin.DslList<com.google.protobuf.Field, FieldsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.fieldsList
      )
    /**
     * `repeated .google.protobuf.Field fields = 2 [json_name = "fields"];`
     * @param value The fields to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addFields")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Field, FieldsProxy>.add(value: com.google.protobuf.Field) {
      _builder.addFields(value)
    }
    /**
     * `repeated .google.protobuf.Field fields = 2 [json_name = "fields"];`
     * @param value The fields to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignFields")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Field, FieldsProxy>.plusAssign(value: com.google.protobuf.Field) {
      add(value)
    }
    /**
     * `repeated .google.protobuf.Field fields = 2 [json_name = "fields"];`
     * @param values The fields to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllFields")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Field, FieldsProxy>.addAll(values: kotlin.collections.Iterable<com.google.protobuf.Field>) {
      _builder.addAllFields(values)
    }
    /**
     * `repeated .google.protobuf.Field fields = 2 [json_name = "fields"];`
     * @param values The fields to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllFields")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Field, FieldsProxy>.plusAssign(values: kotlin.collections.Iterable<com.google.protobuf.Field>) {
      addAll(values)
    }
    /**
     * `repeated .google.protobuf.Field fields = 2 [json_name = "fields"];`
     * @param index The index to set the value at.
     * @param value The fields to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setFields")
    public operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Field, FieldsProxy>.set(index: kotlin.Int, value: com.google.protobuf.Field) {
      _builder.setFields(index, value)
    }
    /**
     * `repeated .google.protobuf.Field fields = 2 [json_name = "fields"];`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearFields")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Field, FieldsProxy>.clear() {
      _builder.clearFields()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class OneofsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated string oneofs = 3 [json_name = "oneofs"];`
     * @return A list containing the oneofs.
     */
    public val oneofs: com.google.protobuf.kotlin.DslList<kotlin.String, OneofsProxy>
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      get() = com.google.protobuf.kotlin.DslList(
        _builder.oneofsList
      )
    /**
     * `repeated string oneofs = 3 [json_name = "oneofs"];`
     * @param value The oneofs to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addOneofs")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, OneofsProxy>.add(value: kotlin.String) {
      _builder.addOneofs(value)
    }
    /**
     * `repeated string oneofs = 3 [json_name = "oneofs"];`
     * @param value The oneofs to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignOneofs")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, OneofsProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * `repeated string oneofs = 3 [json_name = "oneofs"];`
     * @param values The oneofs to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllOneofs")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, OneofsProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllOneofs(values)
    }
    /**
     * `repeated string oneofs = 3 [json_name = "oneofs"];`
     * @param values The oneofs to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllOneofs")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, OneofsProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * `repeated string oneofs = 3 [json_name = "oneofs"];`
     * @param index The index to set the value at.
     * @param value The oneofs to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setOneofs")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, OneofsProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setOneofs(index, value)
    }/**
     * `repeated string oneofs = 3 [json_name = "oneofs"];`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearOneofs")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, OneofsProxy>.clear() {
      _builder.clearOneofs()
    }
    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class OptionsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .google.protobuf.Option options = 4 [json_name = "options"];`
     */
     public val options: com.google.protobuf.kotlin.DslList<com.google.protobuf.Option, OptionsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.optionsList
      )
    /**
     * `repeated .google.protobuf.Option options = 4 [json_name = "options"];`
     * @param value The options to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addOptions")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Option, OptionsProxy>.add(value: com.google.protobuf.Option) {
      _builder.addOptions(value)
    }
    /**
     * `repeated .google.protobuf.Option options = 4 [json_name = "options"];`
     * @param value The options to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignOptions")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Option, OptionsProxy>.plusAssign(value: com.google.protobuf.Option) {
      add(value)
    }
    /**
     * `repeated .google.protobuf.Option options = 4 [json_name = "options"];`
     * @param values The options to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllOptions")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Option, OptionsProxy>.addAll(values: kotlin.collections.Iterable<com.google.protobuf.Option>) {
      _builder.addAllOptions(values)
    }
    /**
     * `repeated .google.protobuf.Option options = 4 [json_name = "options"];`
     * @param values The options to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllOptions")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Option, OptionsProxy>.plusAssign(values: kotlin.collections.Iterable<com.google.protobuf.Option>) {
      addAll(values)
    }
    /**
     * `repeated .google.protobuf.Option options = 4 [json_name = "options"];`
     * @param index The index to set the value at.
     * @param value The options to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setOptions")
    public operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Option, OptionsProxy>.set(index: kotlin.Int, value: com.google.protobuf.Option) {
      _builder.setOptions(index, value)
    }
    /**
     * `repeated .google.protobuf.Option options = 4 [json_name = "options"];`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearOptions")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Option, OptionsProxy>.clear() {
      _builder.clearOptions()
    }

    /**
     * `.google.protobuf.SourceContext source_context = 5 [json_name = "sourceContext"];`
     */
    public var sourceContext: com.google.protobuf.SourceContext
      @JvmName("getSourceContext")
      get() = _builder.sourceContext
      @JvmName("setSourceContext")
      set(value) {
        _builder.sourceContext = value
      }
    /**
     * `.google.protobuf.SourceContext source_context = 5 [json_name = "sourceContext"];`
     */
    public fun clearSourceContext() {
      _builder.clearSourceContext()
    }
    /**
     * `.google.protobuf.SourceContext source_context = 5 [json_name = "sourceContext"];`
     * @return Whether the sourceContext field is set.
     */
    public fun hasSourceContext(): kotlin.Boolean {
      return _builder.hasSourceContext()
    }
    public val TypeKt.Dsl.sourceContextOrNull: com.google.protobuf.SourceContext?
      get() = _builder.sourceContextOrNull

    /**
     * `.google.protobuf.Syntax syntax = 6 [json_name = "syntax"];`
     */
    public var syntax: com.google.protobuf.Syntax
      @JvmName("getSyntax")
      get() = _builder.syntax
      @JvmName("setSyntax")
      set(value) {
        _builder.syntax = value
      }
    public var syntaxValue: kotlin.Int
      @JvmName("getSyntaxValue")
      get() = _builder.syntaxValue
      @JvmName("setSyntaxValue")
      set(value) {
        _builder.syntaxValue = value
      }
    /**
     * `.google.protobuf.Syntax syntax = 6 [json_name = "syntax"];`
     */
    public fun clearSyntax() {
      _builder.clearSyntax()
    }

    /**
     * `string edition = 7 [json_name = "edition"];`
     */
    public var edition: kotlin.String
      @JvmName("getEdition")
      get() = _builder.edition
      @JvmName("setEdition")
      set(value) {
        _builder.edition = value
      }
    /**
     * `string edition = 7 [json_name = "edition"];`
     */
    public fun clearEdition() {
      _builder.clearEdition()
    }
  }
}
public inline fun com.google.protobuf.Type.copy(block: `com.google.protobuf`.TypeKt.Dsl.() -> kotlin.Unit): com.google.protobuf.Type =
  `com.google.protobuf`.TypeKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.google.protobuf.TypeOrBuilder.sourceContextOrNull: com.google.protobuf.SourceContext?
  get() = if (hasSourceContext()) getSourceContext() else null

