// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/protobuf/wrappers.proto
// Protobuf Java Version: 4.28.3

package com.google.protobuf;

public interface UInt32ValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.protobuf.UInt32Value)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>uint32 value = 1 [json_name = "value"];</code>
   * @return The value.
   */
  int getValue();
}
