// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/protobuf/wrappers.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.google.protobuf;

@kotlin.jvm.JvmName("-initializeuInt64Value")
public inline fun uInt64Value(block: com.google.protobuf.UInt64ValueKt.Dsl.() -> kotlin.Unit): com.google.protobuf.UInt64Value =
  com.google.protobuf.UInt64ValueKt.Dsl._create(com.google.protobuf.UInt64Value.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `google.protobuf.UInt64Value`
 */
public object UInt64ValueKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.google.protobuf.UInt64Value.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.google.protobuf.UInt64Value.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.google.protobuf.UInt64Value = _builder.build()

    /**
     * <code>uint64 value = 1 [json_name = "value"];</code>
     */
    public var value: kotlin.Long
      @JvmName("getValue")
      get() = _builder.value
      @JvmName("setValue")
      set(value) {
        _builder.value = value
      }
    /**
     * `uint64 value = 1 [json_name = "value"];`
     */
    public fun clearValue() {
      _builder.clearValue()
    }
  }
}
public inline fun com.google.protobuf.UInt64Value.copy(block: `com.google.protobuf`.UInt64ValueKt.Dsl.() -> kotlin.Unit): com.google.protobuf.UInt64Value =
  `com.google.protobuf`.UInt64ValueKt.Dsl._create(this.toBuilder()).apply { block() }._build()

