// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/protobuf/struct.proto
// Protobuf Java Version: 4.28.3

package com.google.protobuf;

public interface ValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.protobuf.Value)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.google.protobuf.NullValue null_value = 1 [json_name = "nullValue"];</code>
   * @return Whether the nullValue field is set.
   */
  boolean hasNullValue();
  /**
   * <code>.google.protobuf.NullValue null_value = 1 [json_name = "nullValue"];</code>
   * @return The enum numeric value on the wire for nullValue.
   */
  int getNullValueValue();
  /**
   * <code>.google.protobuf.NullValue null_value = 1 [json_name = "nullValue"];</code>
   * @return The nullValue.
   */
  com.google.protobuf.NullValue getNullValue();

  /**
   * <code>double number_value = 2 [json_name = "numberValue"];</code>
   * @return Whether the numberValue field is set.
   */
  boolean hasNumberValue();
  /**
   * <code>double number_value = 2 [json_name = "numberValue"];</code>
   * @return The numberValue.
   */
  double getNumberValue();

  /**
   * <code>string string_value = 3 [json_name = "stringValue"];</code>
   * @return Whether the stringValue field is set.
   */
  boolean hasStringValue();
  /**
   * <code>string string_value = 3 [json_name = "stringValue"];</code>
   * @return The stringValue.
   */
  java.lang.String getStringValue();
  /**
   * <code>string string_value = 3 [json_name = "stringValue"];</code>
   * @return The bytes for stringValue.
   */
  com.google.protobuf.ByteString
      getStringValueBytes();

  /**
   * <code>bool bool_value = 4 [json_name = "boolValue"];</code>
   * @return Whether the boolValue field is set.
   */
  boolean hasBoolValue();
  /**
   * <code>bool bool_value = 4 [json_name = "boolValue"];</code>
   * @return The boolValue.
   */
  boolean getBoolValue();

  /**
   * <code>.google.protobuf.Struct struct_value = 5 [json_name = "structValue"];</code>
   * @return Whether the structValue field is set.
   */
  boolean hasStructValue();
  /**
   * <code>.google.protobuf.Struct struct_value = 5 [json_name = "structValue"];</code>
   * @return The structValue.
   */
  com.google.protobuf.Struct getStructValue();

  /**
   * <code>.google.protobuf.ListValue list_value = 6 [json_name = "listValue"];</code>
   * @return Whether the listValue field is set.
   */
  boolean hasListValue();
  /**
   * <code>.google.protobuf.ListValue list_value = 6 [json_name = "listValue"];</code>
   * @return The listValue.
   */
  com.google.protobuf.ListValue getListValue();

  public com.google.protobuf.Value.KindCase getKindCase();
}
